-- hps_subsys.vhd

-- Generated using ACDS version 26.1 110

library IEEE;
library agilex_hps;
library emif_io96b_hps;
library hps_subsys_s10_user_rst_clkgate_0;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hps_subsys is
	port (
		h2f_reset_reset                       : out   std_logic;                                        --                 h2f_reset.reset
		lwhps2fpga_axi_clock_clk              : in    std_logic                     := '0';             --      lwhps2fpga_axi_clock.clk
		lwhps2fpga_axi_reset_reset            : in    std_logic                     := '0';             --      lwhps2fpga_axi_reset.reset
		lwhps2fpga_awid                       : out   std_logic_vector(3 downto 0);                     --                lwhps2fpga.awid
		lwhps2fpga_awaddr                     : out   std_logic_vector(28 downto 0);                    --                          .awaddr
		lwhps2fpga_awlen                      : out   std_logic_vector(7 downto 0);                     --                          .awlen
		lwhps2fpga_awsize                     : out   std_logic_vector(2 downto 0);                     --                          .awsize
		lwhps2fpga_awburst                    : out   std_logic_vector(1 downto 0);                     --                          .awburst
		lwhps2fpga_awlock                     : out   std_logic;                                        --                          .awlock
		lwhps2fpga_awcache                    : out   std_logic_vector(3 downto 0);                     --                          .awcache
		lwhps2fpga_awprot                     : out   std_logic_vector(2 downto 0);                     --                          .awprot
		lwhps2fpga_awvalid                    : out   std_logic;                                        --                          .awvalid
		lwhps2fpga_awready                    : in    std_logic                     := '0';             --                          .awready
		lwhps2fpga_wdata                      : out   std_logic_vector(31 downto 0);                    --                          .wdata
		lwhps2fpga_wstrb                      : out   std_logic_vector(3 downto 0);                     --                          .wstrb
		lwhps2fpga_wlast                      : out   std_logic;                                        --                          .wlast
		lwhps2fpga_wvalid                     : out   std_logic;                                        --                          .wvalid
		lwhps2fpga_wready                     : in    std_logic                     := '0';             --                          .wready
		lwhps2fpga_bid                        : in    std_logic_vector(3 downto 0)  := (others => '0'); --                          .bid
		lwhps2fpga_bresp                      : in    std_logic_vector(1 downto 0)  := (others => '0'); --                          .bresp
		lwhps2fpga_bvalid                     : in    std_logic                     := '0';             --                          .bvalid
		lwhps2fpga_bready                     : out   std_logic;                                        --                          .bready
		lwhps2fpga_arid                       : out   std_logic_vector(3 downto 0);                     --                          .arid
		lwhps2fpga_araddr                     : out   std_logic_vector(28 downto 0);                    --                          .araddr
		lwhps2fpga_arlen                      : out   std_logic_vector(7 downto 0);                     --                          .arlen
		lwhps2fpga_arsize                     : out   std_logic_vector(2 downto 0);                     --                          .arsize
		lwhps2fpga_arburst                    : out   std_logic_vector(1 downto 0);                     --                          .arburst
		lwhps2fpga_arlock                     : out   std_logic;                                        --                          .arlock
		lwhps2fpga_arcache                    : out   std_logic_vector(3 downto 0);                     --                          .arcache
		lwhps2fpga_arprot                     : out   std_logic_vector(2 downto 0);                     --                          .arprot
		lwhps2fpga_arvalid                    : out   std_logic;                                        --                          .arvalid
		lwhps2fpga_arready                    : in    std_logic                     := '0';             --                          .arready
		lwhps2fpga_rid                        : in    std_logic_vector(3 downto 0)  := (others => '0'); --                          .rid
		lwhps2fpga_rdata                      : in    std_logic_vector(31 downto 0) := (others => '0'); --                          .rdata
		lwhps2fpga_rresp                      : in    std_logic_vector(1 downto 0)  := (others => '0'); --                          .rresp
		lwhps2fpga_rlast                      : in    std_logic                     := '0';             --                          .rlast
		lwhps2fpga_rvalid                     : in    std_logic                     := '0';             --                          .rvalid
		lwhps2fpga_rready                     : out   std_logic;                                        --                          .rready
		hps_uart0_cts_n                       : in    std_logic                     := '0';             --                 hps_uart0.cts_n
		hps_uart0_dcd_n                       : in    std_logic                     := '0';             --                          .dcd_n
		hps_uart0_dsr_n                       : in    std_logic                     := '0';             --                          .dsr_n
		hps_uart0_dtr_n                       : out   std_logic;                                        --                          .dtr_n
		hps_uart0_out1_n                      : out   std_logic;                                        --                          .out1_n
		hps_uart0_out2_n                      : out   std_logic;                                        --                          .out2_n
		hps_uart0_ri_n                        : in    std_logic                     := '0';             --                          .ri_n
		hps_uart0_rts_n                       : out   std_logic;                                        --                          .rts_n
		hps_uart0_rx                          : in    std_logic                     := '0';             --                          .rx
		hps_uart0_tx                          : out   std_logic;                                        --                          .tx
		hps_io_hps_osc_clk                    : in    std_logic                     := '0';             --                    hps_io.hps_osc_clk
		hps_io_sdmmc_data0                    : inout std_logic                     := '0';             --                          .sdmmc_data0
		hps_io_sdmmc_data1                    : inout std_logic                     := '0';             --                          .sdmmc_data1
		hps_io_sdmmc_cclk                     : out   std_logic;                                        --                          .sdmmc_cclk
		hps_io_sdmmc_data2                    : inout std_logic                     := '0';             --                          .sdmmc_data2
		hps_io_sdmmc_data3                    : inout std_logic                     := '0';             --                          .sdmmc_data3
		hps_io_sdmmc_cmd                      : inout std_logic                     := '0';             --                          .sdmmc_cmd
		hps_io_emac0_tx_clk                   : out   std_logic;                                        --                          .emac0_tx_clk
		hps_io_emac0_tx_ctl                   : out   std_logic;                                        --                          .emac0_tx_ctl
		hps_io_emac0_rx_clk                   : in    std_logic                     := '0';             --                          .emac0_rx_clk
		hps_io_emac0_rx_ctl                   : in    std_logic                     := '0';             --                          .emac0_rx_ctl
		hps_io_emac0_txd0                     : out   std_logic;                                        --                          .emac0_txd0
		hps_io_emac0_txd1                     : out   std_logic;                                        --                          .emac0_txd1
		hps_io_emac0_rxd0                     : in    std_logic                     := '0';             --                          .emac0_rxd0
		hps_io_emac0_rxd1                     : in    std_logic                     := '0';             --                          .emac0_rxd1
		hps_io_emac0_txd2                     : out   std_logic;                                        --                          .emac0_txd2
		hps_io_emac0_txd3                     : out   std_logic;                                        --                          .emac0_txd3
		hps_io_emac0_rxd2                     : in    std_logic                     := '0';             --                          .emac0_rxd2
		hps_io_emac0_rxd3                     : in    std_logic                     := '0';             --                          .emac0_rxd3
		hps_io_mdio0_mdio                     : inout std_logic                     := '0';             --                          .mdio0_mdio
		hps_io_mdio0_mdc                      : out   std_logic;                                        --                          .mdio0_mdc
		hps_io_uart1_tx                       : out   std_logic;                                        --                          .uart1_tx
		hps_io_uart1_rx                       : in    std_logic                     := '0';             --                          .uart1_rx
		hps_io_gpio40                         : inout std_logic                     := '0';             --                          .gpio40
		hps_io_gpio41                         : inout std_logic                     := '0';             --                          .gpio41
		f2h_irq1_in_irq                       : in    std_logic_vector(31 downto 0) := (others => '0'); --               f2h_irq1_in.irq
		f2h_irq0_in_irq                       : in    std_logic_vector(31 downto 0) := (others => '0'); --               f2h_irq0_in.irq
		emif_hps_emif_mem_0_mem_cs            : out   std_logic_vector(0 downto 0);                     --       emif_hps_emif_mem_0.mem_cs
		emif_hps_emif_mem_0_mem_ca            : out   std_logic_vector(5 downto 0);                     --                          .mem_ca
		emif_hps_emif_mem_0_mem_cke           : out   std_logic_vector(0 downto 0);                     --                          .mem_cke
		emif_hps_emif_mem_0_mem_dq            : inout std_logic_vector(31 downto 0) := (others => '0'); --                          .mem_dq
		emif_hps_emif_mem_0_mem_dqs_t         : inout std_logic_vector(3 downto 0)  := (others => '0'); --                          .mem_dqs_t
		emif_hps_emif_mem_0_mem_dqs_c         : inout std_logic_vector(3 downto 0)  := (others => '0'); --                          .mem_dqs_c
		emif_hps_emif_mem_0_mem_dmi           : inout std_logic_vector(3 downto 0)  := (others => '0'); --                          .mem_dmi
		emif_hps_emif_mem_ck_0_mem_ck_t       : out   std_logic_vector(0 downto 0);                     --    emif_hps_emif_mem_ck_0.mem_ck_t
		emif_hps_emif_mem_ck_0_mem_ck_c       : out   std_logic_vector(0 downto 0);                     --                          .mem_ck_c
		emif_hps_emif_mem_reset_n_mem_reset_n : out   std_logic;                                        -- emif_hps_emif_mem_reset_n.mem_reset_n
		emif_hps_emif_oct_0_oct_rzqin         : in    std_logic                     := '0';             --       emif_hps_emif_oct_0.oct_rzqin
		emif_hps_emif_ref_clk_clk             : in    std_logic                     := '0';             --     emif_hps_emif_ref_clk.clk
		ninit_done_reset                      : out   std_logic                                         --                ninit_done.reset
	);
end entity hps_subsys;

architecture rtl of hps_subsys is
	component agilex_hps_cmp is
		port (
			h2f_reset_reset                : out   std_logic;                                         -- reset
			lwhps2fpga_axi_clock_clk       : in    std_logic                      := 'X';             -- clk
			lwhps2fpga_axi_reset_reset     : in    std_logic                      := 'X';             -- reset
			lwhps2fpga_awid                : out   std_logic_vector(3 downto 0);                      -- awid
			lwhps2fpga_awaddr              : out   std_logic_vector(28 downto 0);                     -- awaddr
			lwhps2fpga_awlen               : out   std_logic_vector(7 downto 0);                      -- awlen
			lwhps2fpga_awsize              : out   std_logic_vector(2 downto 0);                      -- awsize
			lwhps2fpga_awburst             : out   std_logic_vector(1 downto 0);                      -- awburst
			lwhps2fpga_awlock              : out   std_logic;                                         -- awlock
			lwhps2fpga_awcache             : out   std_logic_vector(3 downto 0);                      -- awcache
			lwhps2fpga_awprot              : out   std_logic_vector(2 downto 0);                      -- awprot
			lwhps2fpga_awvalid             : out   std_logic;                                         -- awvalid
			lwhps2fpga_awready             : in    std_logic                      := 'X';             -- awready
			lwhps2fpga_wdata               : out   std_logic_vector(31 downto 0);                     -- wdata
			lwhps2fpga_wstrb               : out   std_logic_vector(3 downto 0);                      -- wstrb
			lwhps2fpga_wlast               : out   std_logic;                                         -- wlast
			lwhps2fpga_wvalid              : out   std_logic;                                         -- wvalid
			lwhps2fpga_wready              : in    std_logic                      := 'X';             -- wready
			lwhps2fpga_bid                 : in    std_logic_vector(3 downto 0)   := (others => 'X'); -- bid
			lwhps2fpga_bresp               : in    std_logic_vector(1 downto 0)   := (others => 'X'); -- bresp
			lwhps2fpga_bvalid              : in    std_logic                      := 'X';             -- bvalid
			lwhps2fpga_bready              : out   std_logic;                                         -- bready
			lwhps2fpga_arid                : out   std_logic_vector(3 downto 0);                      -- arid
			lwhps2fpga_araddr              : out   std_logic_vector(28 downto 0);                     -- araddr
			lwhps2fpga_arlen               : out   std_logic_vector(7 downto 0);                      -- arlen
			lwhps2fpga_arsize              : out   std_logic_vector(2 downto 0);                      -- arsize
			lwhps2fpga_arburst             : out   std_logic_vector(1 downto 0);                      -- arburst
			lwhps2fpga_arlock              : out   std_logic;                                         -- arlock
			lwhps2fpga_arcache             : out   std_logic_vector(3 downto 0);                      -- arcache
			lwhps2fpga_arprot              : out   std_logic_vector(2 downto 0);                      -- arprot
			lwhps2fpga_arvalid             : out   std_logic;                                         -- arvalid
			lwhps2fpga_arready             : in    std_logic                      := 'X';             -- arready
			lwhps2fpga_rid                 : in    std_logic_vector(3 downto 0)   := (others => 'X'); -- rid
			lwhps2fpga_rdata               : in    std_logic_vector(31 downto 0)  := (others => 'X'); -- rdata
			lwhps2fpga_rresp               : in    std_logic_vector(1 downto 0)   := (others => 'X'); -- rresp
			lwhps2fpga_rlast               : in    std_logic                      := 'X';             -- rlast
			lwhps2fpga_rvalid              : in    std_logic                      := 'X';             -- rvalid
			lwhps2fpga_rready              : out   std_logic;                                         -- rready
			emac0_app_rst_reset_n          : out   std_logic;                                         -- reset_n
			uart0_cts_n                    : in    std_logic                      := 'X';             -- cts_n
			uart0_dcd_n                    : in    std_logic                      := 'X';             -- dcd_n
			uart0_dsr_n                    : in    std_logic                      := 'X';             -- dsr_n
			uart0_dtr_n                    : out   std_logic;                                         -- dtr_n
			uart0_out1_n                   : out   std_logic;                                         -- out1_n
			uart0_out2_n                   : out   std_logic;                                         -- out2_n
			uart0_ri_n                     : in    std_logic                      := 'X';             -- ri_n
			uart0_rts_n                    : out   std_logic;                                         -- rts_n
			uart0_rx                       : in    std_logic                      := 'X';             -- rx
			uart0_tx                       : out   std_logic;                                         -- tx
			hps_io_hps_osc_clk             : in    std_logic                      := 'X';             -- hps_osc_clk
			hps_io_sdmmc_data0             : inout std_logic                      := 'X';             -- sdmmc_data0
			hps_io_sdmmc_data1             : inout std_logic                      := 'X';             -- sdmmc_data1
			hps_io_sdmmc_cclk              : out   std_logic;                                         -- sdmmc_cclk
			hps_io_sdmmc_data2             : inout std_logic                      := 'X';             -- sdmmc_data2
			hps_io_sdmmc_data3             : inout std_logic                      := 'X';             -- sdmmc_data3
			hps_io_sdmmc_cmd               : inout std_logic                      := 'X';             -- sdmmc_cmd
			hps_io_emac0_tx_clk            : out   std_logic;                                         -- emac0_tx_clk
			hps_io_emac0_tx_ctl            : out   std_logic;                                         -- emac0_tx_ctl
			hps_io_emac0_rx_clk            : in    std_logic                      := 'X';             -- emac0_rx_clk
			hps_io_emac0_rx_ctl            : in    std_logic                      := 'X';             -- emac0_rx_ctl
			hps_io_emac0_txd0              : out   std_logic;                                         -- emac0_txd0
			hps_io_emac0_txd1              : out   std_logic;                                         -- emac0_txd1
			hps_io_emac0_rxd0              : in    std_logic                      := 'X';             -- emac0_rxd0
			hps_io_emac0_rxd1              : in    std_logic                      := 'X';             -- emac0_rxd1
			hps_io_emac0_txd2              : out   std_logic;                                         -- emac0_txd2
			hps_io_emac0_txd3              : out   std_logic;                                         -- emac0_txd3
			hps_io_emac0_rxd2              : in    std_logic                      := 'X';             -- emac0_rxd2
			hps_io_emac0_rxd3              : in    std_logic                      := 'X';             -- emac0_rxd3
			hps_io_mdio0_mdio              : inout std_logic                      := 'X';             -- mdio0_mdio
			hps_io_mdio0_mdc               : out   std_logic;                                         -- mdio0_mdc
			hps_io_uart1_tx                : out   std_logic;                                         -- uart1_tx
			hps_io_uart1_rx                : in    std_logic                      := 'X';             -- uart1_rx
			hps_io_gpio40                  : inout std_logic                      := 'X';             -- gpio40
			hps_io_gpio41                  : inout std_logic                      := 'X';             -- gpio41
			fpga2hps_interrupt_irq1_irq    : in    std_logic_vector(31 downto 0)  := (others => 'X'); -- irq
			fpga2hps_interrupt_irq0_irq    : in    std_logic_vector(31 downto 0)  := (others => 'X'); -- irq
			io96b0_to_hps_ch0_axil_clk     : in    std_logic                      := 'X';             -- ch0_axil_clk
			io96b0_to_hps_ch0_axil_reset_n : in    std_logic                      := 'X';             -- ch0_axil_reset_n
			io96b0_to_hps_ch0_axil_arready : in    std_logic                      := 'X';             -- ch0_axil_arready
			io96b0_to_hps_ch0_axil_awready : in    std_logic                      := 'X';             -- ch0_axil_awready
			io96b0_to_hps_ch0_axil_bresp   : in    std_logic_vector(1 downto 0)   := (others => 'X'); -- ch0_axil_bresp
			io96b0_to_hps_ch0_axil_bvalid  : in    std_logic                      := 'X';             -- ch0_axil_bvalid
			io96b0_to_hps_ch0_axil_rdata   : in    std_logic_vector(31 downto 0)  := (others => 'X'); -- ch0_axil_rdata
			io96b0_to_hps_ch0_axil_rresp   : in    std_logic_vector(1 downto 0)   := (others => 'X'); -- ch0_axil_rresp
			io96b0_to_hps_ch0_axil_rvalid  : in    std_logic                      := 'X';             -- ch0_axil_rvalid
			io96b0_to_hps_ch0_axil_wready  : in    std_logic                      := 'X';             -- ch0_axil_wready
			io96b0_to_hps_ch0_axil_araddr  : out   std_logic_vector(26 downto 0);                     -- ch0_axil_araddr
			io96b0_to_hps_ch0_axil_arvalid : out   std_logic;                                         -- ch0_axil_arvalid
			io96b0_to_hps_ch0_axil_awaddr  : out   std_logic_vector(26 downto 0);                     -- ch0_axil_awaddr
			io96b0_to_hps_ch0_axil_awvalid : out   std_logic;                                         -- ch0_axil_awvalid
			io96b0_to_hps_ch0_axil_bready  : out   std_logic;                                         -- ch0_axil_bready
			io96b0_to_hps_ch0_axil_rready  : out   std_logic;                                         -- ch0_axil_rready
			io96b0_to_hps_ch0_axil_wdata   : out   std_logic_vector(31 downto 0);                     -- ch0_axil_wdata
			io96b0_to_hps_ch0_axil_wstrb   : out   std_logic_vector(3 downto 0);                      -- ch0_axil_wstrb
			io96b0_to_hps_ch0_axil_wvalid  : out   std_logic;                                         -- ch0_axil_wvalid
			io96b0_to_hps_ch0_axil_arprot  : out   std_logic_vector(2 downto 0);                      -- ch0_axil_arprot
			io96b0_to_hps_ch0_axil_awprot  : out   std_logic_vector(2 downto 0);                      -- ch0_axil_awprot
			io96b0_to_hps_axi4_ch0_clk     : in    std_logic                      := 'X';             -- axi4_ch0_clk
			io96b0_to_hps_axi4_ch0_reset_n : in    std_logic                      := 'X';             -- axi4_ch0_reset_n
			io96b0_to_hps_axi4_ch0_arready : in    std_logic                      := 'X';             -- axi4_ch0_arready
			io96b0_to_hps_axi4_ch0_awready : in    std_logic                      := 'X';             -- axi4_ch0_awready
			io96b0_to_hps_axi4_ch0_bid     : in    std_logic_vector(6 downto 0)   := (others => 'X'); -- axi4_ch0_bid
			io96b0_to_hps_axi4_ch0_bresp   : in    std_logic_vector(1 downto 0)   := (others => 'X'); -- axi4_ch0_bresp
			io96b0_to_hps_axi4_ch0_bvalid  : in    std_logic                      := 'X';             -- axi4_ch0_bvalid
			io96b0_to_hps_axi4_ch0_rdata   : in    std_logic_vector(255 downto 0) := (others => 'X'); -- axi4_ch0_rdata
			io96b0_to_hps_axi4_ch0_rid     : in    std_logic_vector(6 downto 0)   := (others => 'X'); -- axi4_ch0_rid
			io96b0_to_hps_axi4_ch0_rlast   : in    std_logic                      := 'X';             -- axi4_ch0_rlast
			io96b0_to_hps_axi4_ch0_rresp   : in    std_logic_vector(1 downto 0)   := (others => 'X'); -- axi4_ch0_rresp
			io96b0_to_hps_axi4_ch0_ruser   : in    std_logic_vector(31 downto 0)  := (others => 'X'); -- axi4_ch0_ruser
			io96b0_to_hps_axi4_ch0_rvalid  : in    std_logic                      := 'X';             -- axi4_ch0_rvalid
			io96b0_to_hps_axi4_ch0_wready  : in    std_logic                      := 'X';             -- axi4_ch0_wready
			io96b0_to_hps_axi4_ch0_araddr  : out   std_logic_vector(39 downto 0);                     -- axi4_ch0_araddr
			io96b0_to_hps_axi4_ch0_arburst : out   std_logic_vector(1 downto 0);                      -- axi4_ch0_arburst
			io96b0_to_hps_axi4_ch0_arid    : out   std_logic_vector(6 downto 0);                      -- axi4_ch0_arid
			io96b0_to_hps_axi4_ch0_arlen   : out   std_logic_vector(7 downto 0);                      -- axi4_ch0_arlen
			io96b0_to_hps_axi4_ch0_arlock  : out   std_logic;                                         -- axi4_ch0_arlock
			io96b0_to_hps_axi4_ch0_arqos   : out   std_logic_vector(3 downto 0);                      -- axi4_ch0_arqos
			io96b0_to_hps_axi4_ch0_arsize  : out   std_logic_vector(2 downto 0);                      -- axi4_ch0_arsize
			io96b0_to_hps_axi4_ch0_aruser  : out   std_logic_vector(13 downto 0);                     -- axi4_ch0_aruser
			io96b0_to_hps_axi4_ch0_arvalid : out   std_logic;                                         -- axi4_ch0_arvalid
			io96b0_to_hps_axi4_ch0_awaddr  : out   std_logic_vector(39 downto 0);                     -- axi4_ch0_awaddr
			io96b0_to_hps_axi4_ch0_awburst : out   std_logic_vector(1 downto 0);                      -- axi4_ch0_awburst
			io96b0_to_hps_axi4_ch0_awid    : out   std_logic_vector(6 downto 0);                      -- axi4_ch0_awid
			io96b0_to_hps_axi4_ch0_awlen   : out   std_logic_vector(7 downto 0);                      -- axi4_ch0_awlen
			io96b0_to_hps_axi4_ch0_awlock  : out   std_logic;                                         -- axi4_ch0_awlock
			io96b0_to_hps_axi4_ch0_awqos   : out   std_logic_vector(3 downto 0);                      -- axi4_ch0_awqos
			io96b0_to_hps_axi4_ch0_awsize  : out   std_logic_vector(2 downto 0);                      -- axi4_ch0_awsize
			io96b0_to_hps_axi4_ch0_awuser  : out   std_logic_vector(13 downto 0);                     -- axi4_ch0_awuser
			io96b0_to_hps_axi4_ch0_awvalid : out   std_logic;                                         -- axi4_ch0_awvalid
			io96b0_to_hps_axi4_ch0_bready  : out   std_logic;                                         -- axi4_ch0_bready
			io96b0_to_hps_axi4_ch0_rready  : out   std_logic;                                         -- axi4_ch0_rready
			io96b0_to_hps_axi4_ch0_wdata   : out   std_logic_vector(255 downto 0);                    -- axi4_ch0_wdata
			io96b0_to_hps_axi4_ch0_wlast   : out   std_logic;                                         -- axi4_ch0_wlast
			io96b0_to_hps_axi4_ch0_wstrb   : out   std_logic_vector(31 downto 0);                     -- axi4_ch0_wstrb
			io96b0_to_hps_axi4_ch0_wuser   : out   std_logic_vector(31 downto 0);                     -- axi4_ch0_wuser
			io96b0_to_hps_axi4_ch0_wvalid  : out   std_logic;                                         -- axi4_ch0_wvalid
			io96b0_to_hps_axi4_ch0_arprot  : out   std_logic_vector(2 downto 0);                      -- axi4_ch0_arprot
			io96b0_to_hps_axi4_ch0_awprot  : out   std_logic_vector(2 downto 0)                       -- axi4_ch0_awprot
		);
	end component agilex_hps_cmp;

	component emif_io96b_hps_cmp is
		port (
			s0_noc_axi4lite_clock   : out   std_logic;                                         -- ch0_axil_clk
			s0_noc_axi4lite_reset_n : out   std_logic;                                         -- ch0_axil_reset_n
			s0_noc_axi4lite_awaddr  : in    std_logic_vector(26 downto 0)  := (others => 'X'); -- ch0_axil_awaddr
			s0_noc_axi4lite_awvalid : in    std_logic                      := 'X';             -- ch0_axil_awvalid
			s0_noc_axi4lite_awready : out   std_logic;                                         -- ch0_axil_awready
			s0_noc_axi4lite_araddr  : in    std_logic_vector(26 downto 0)  := (others => 'X'); -- ch0_axil_araddr
			s0_noc_axi4lite_arvalid : in    std_logic                      := 'X';             -- ch0_axil_arvalid
			s0_noc_axi4lite_arready : out   std_logic;                                         -- ch0_axil_arready
			s0_noc_axi4lite_wdata   : in    std_logic_vector(31 downto 0)  := (others => 'X'); -- ch0_axil_wdata
			s0_noc_axi4lite_wvalid  : in    std_logic                      := 'X';             -- ch0_axil_wvalid
			s0_noc_axi4lite_wready  : out   std_logic;                                         -- ch0_axil_wready
			s0_noc_axi4lite_rresp   : out   std_logic_vector(1 downto 0);                      -- ch0_axil_rresp
			s0_noc_axi4lite_rdata   : out   std_logic_vector(31 downto 0);                     -- ch0_axil_rdata
			s0_noc_axi4lite_rvalid  : out   std_logic;                                         -- ch0_axil_rvalid
			s0_noc_axi4lite_rready  : in    std_logic                      := 'X';             -- ch0_axil_rready
			s0_noc_axi4lite_bresp   : out   std_logic_vector(1 downto 0);                      -- ch0_axil_bresp
			s0_noc_axi4lite_bvalid  : out   std_logic;                                         -- ch0_axil_bvalid
			s0_noc_axi4lite_bready  : in    std_logic                      := 'X';             -- ch0_axil_bready
			s0_noc_axi4lite_awprot  : in    std_logic_vector(2 downto 0)   := (others => 'X'); -- ch0_axil_awprot
			s0_noc_axi4lite_arprot  : in    std_logic_vector(2 downto 0)   := (others => 'X'); -- ch0_axil_arprot
			s0_noc_axi4lite_wstrb   : in    std_logic_vector(3 downto 0)   := (others => 'X'); -- ch0_axil_wstrb
			s0_axi4_awaddr          : in    std_logic_vector(39 downto 0)  := (others => 'X'); -- axi4_ch0_awaddr
			s0_axi4_awburst         : in    std_logic_vector(1 downto 0)   := (others => 'X'); -- axi4_ch0_awburst
			s0_axi4_awid            : in    std_logic_vector(6 downto 0)   := (others => 'X'); -- axi4_ch0_awid
			s0_axi4_awlen           : in    std_logic_vector(7 downto 0)   := (others => 'X'); -- axi4_ch0_awlen
			s0_axi4_awlock          : in    std_logic                      := 'X';             -- axi4_ch0_awlock
			s0_axi4_awqos           : in    std_logic_vector(3 downto 0)   := (others => 'X'); -- axi4_ch0_awqos
			s0_axi4_awsize          : in    std_logic_vector(2 downto 0)   := (others => 'X'); -- axi4_ch0_awsize
			s0_axi4_awvalid         : in    std_logic                      := 'X';             -- axi4_ch0_awvalid
			s0_axi4_awuser          : in    std_logic_vector(13 downto 0)  := (others => 'X'); -- axi4_ch0_awuser
			s0_axi4_awprot          : in    std_logic_vector(2 downto 0)   := (others => 'X'); -- axi4_ch0_awprot
			s0_axi4_awready         : out   std_logic;                                         -- axi4_ch0_awready
			s0_axi4_araddr          : in    std_logic_vector(39 downto 0)  := (others => 'X'); -- axi4_ch0_araddr
			s0_axi4_arburst         : in    std_logic_vector(1 downto 0)   := (others => 'X'); -- axi4_ch0_arburst
			s0_axi4_arid            : in    std_logic_vector(6 downto 0)   := (others => 'X'); -- axi4_ch0_arid
			s0_axi4_arlen           : in    std_logic_vector(7 downto 0)   := (others => 'X'); -- axi4_ch0_arlen
			s0_axi4_arlock          : in    std_logic                      := 'X';             -- axi4_ch0_arlock
			s0_axi4_arqos           : in    std_logic_vector(3 downto 0)   := (others => 'X'); -- axi4_ch0_arqos
			s0_axi4_arsize          : in    std_logic_vector(2 downto 0)   := (others => 'X'); -- axi4_ch0_arsize
			s0_axi4_arvalid         : in    std_logic                      := 'X';             -- axi4_ch0_arvalid
			s0_axi4_aruser          : in    std_logic_vector(13 downto 0)  := (others => 'X'); -- axi4_ch0_aruser
			s0_axi4_arprot          : in    std_logic_vector(2 downto 0)   := (others => 'X'); -- axi4_ch0_arprot
			s0_axi4_arready         : out   std_logic;                                         -- axi4_ch0_arready
			s0_axi4_wdata           : in    std_logic_vector(255 downto 0) := (others => 'X'); -- axi4_ch0_wdata
			s0_axi4_wstrb           : in    std_logic_vector(31 downto 0)  := (others => 'X'); -- axi4_ch0_wstrb
			s0_axi4_wlast           : in    std_logic                      := 'X';             -- axi4_ch0_wlast
			s0_axi4_wvalid          : in    std_logic                      := 'X';             -- axi4_ch0_wvalid
			s0_axi4_wready          : out   std_logic;                                         -- axi4_ch0_wready
			s0_axi4_bready          : in    std_logic                      := 'X';             -- axi4_ch0_bready
			s0_axi4_bid             : out   std_logic_vector(6 downto 0);                      -- axi4_ch0_bid
			s0_axi4_bresp           : out   std_logic_vector(1 downto 0);                      -- axi4_ch0_bresp
			s0_axi4_bvalid          : out   std_logic;                                         -- axi4_ch0_bvalid
			s0_axi4_rready          : in    std_logic                      := 'X';             -- axi4_ch0_rready
			s0_axi4_rdata           : out   std_logic_vector(255 downto 0);                    -- axi4_ch0_rdata
			s0_axi4_rid             : out   std_logic_vector(6 downto 0);                      -- axi4_ch0_rid
			s0_axi4_rlast           : out   std_logic;                                         -- axi4_ch0_rlast
			s0_axi4_rresp           : out   std_logic_vector(1 downto 0);                      -- axi4_ch0_rresp
			s0_axi4_rvalid          : out   std_logic;                                         -- axi4_ch0_rvalid
			noc_aclk_0              : out   std_logic;                                         -- axi4_ch0_clk
			noc_rst_n_0             : out   std_logic;                                         -- axi4_ch0_reset_n
			s0_axi4_wuser           : in    std_logic_vector(31 downto 0)  := (others => 'X'); -- axi4_ch0_wuser
			s0_axi4_ruser           : out   std_logic_vector(31 downto 0);                     -- axi4_ch0_ruser
			mem_0_cs                : out   std_logic_vector(0 downto 0);                      -- mem_cs
			mem_0_ca                : out   std_logic_vector(5 downto 0);                      -- mem_ca
			mem_0_cke               : out   std_logic_vector(0 downto 0);                      -- mem_cke
			mem_0_dq                : inout std_logic_vector(31 downto 0)  := (others => 'X'); -- mem_dq
			mem_0_dqs_t             : inout std_logic_vector(3 downto 0)   := (others => 'X'); -- mem_dqs_t
			mem_0_dqs_c             : inout std_logic_vector(3 downto 0)   := (others => 'X'); -- mem_dqs_c
			mem_0_dmi               : inout std_logic_vector(3 downto 0)   := (others => 'X'); -- mem_dmi
			mem_0_ck_t              : out   std_logic_vector(0 downto 0);                      -- mem_ck_t
			mem_0_ck_c              : out   std_logic_vector(0 downto 0);                      -- mem_ck_c
			mem_0_reset_n           : out   std_logic;                                         -- mem_reset_n
			oct_rzqin_0             : in    std_logic                      := 'X';             -- oct_rzqin
			ref_clk                 : in    std_logic                      := 'X'              -- clk
		);
	end component emif_io96b_hps_cmp;

	component hps_subsys_s10_user_rst_clkgate_0_cmp is
		port (
			ninit_done : out std_logic   -- reset
		);
	end component hps_subsys_s10_user_rst_clkgate_0_cmp;

	signal emif_hps_io96b0_to_hps_ch0_axil_rvalid    : std_logic;                      -- emif_hps:s0_noc_axi4lite_rvalid -> agilex_hps:io96b0_to_hps_ch0_axil_rvalid
	signal agilex_hps_io96b0_to_hps_axi4_ch0_awprot  : std_logic_vector(2 downto 0);   -- agilex_hps:io96b0_to_hps_axi4_ch0_awprot -> emif_hps:s0_axi4_awprot
	signal agilex_hps_io96b0_to_hps_axi4_ch0_arvalid : std_logic;                      -- agilex_hps:io96b0_to_hps_axi4_ch0_arvalid -> emif_hps:s0_axi4_arvalid
	signal agilex_hps_io96b0_to_hps_axi4_ch0_bready  : std_logic;                      -- agilex_hps:io96b0_to_hps_axi4_ch0_bready -> emif_hps:s0_axi4_bready
	signal agilex_hps_io96b0_to_hps_axi4_ch0_arlock  : std_logic;                      -- agilex_hps:io96b0_to_hps_axi4_ch0_arlock -> emif_hps:s0_axi4_arlock
	signal agilex_hps_io96b0_to_hps_ch0_axil_arprot  : std_logic_vector(2 downto 0);   -- agilex_hps:io96b0_to_hps_ch0_axil_arprot -> emif_hps:s0_noc_axi4lite_arprot
	signal agilex_hps_io96b0_to_hps_axi4_ch0_awaddr  : std_logic_vector(39 downto 0);  -- agilex_hps:io96b0_to_hps_axi4_ch0_awaddr -> emif_hps:s0_axi4_awaddr
	signal agilex_hps_io96b0_to_hps_axi4_ch0_awvalid : std_logic;                      -- agilex_hps:io96b0_to_hps_axi4_ch0_awvalid -> emif_hps:s0_axi4_awvalid
	signal agilex_hps_io96b0_to_hps_ch0_axil_wvalid  : std_logic;                      -- agilex_hps:io96b0_to_hps_ch0_axil_wvalid -> emif_hps:s0_noc_axi4lite_wvalid
	signal agilex_hps_io96b0_to_hps_ch0_axil_araddr  : std_logic_vector(26 downto 0);  -- agilex_hps:io96b0_to_hps_ch0_axil_araddr -> emif_hps:s0_noc_axi4lite_araddr
	signal agilex_hps_io96b0_to_hps_axi4_ch0_awid    : std_logic_vector(6 downto 0);   -- agilex_hps:io96b0_to_hps_axi4_ch0_awid -> emif_hps:s0_axi4_awid
	signal emif_hps_io96b0_to_hps_ch0_axil_rresp     : std_logic_vector(1 downto 0);   -- emif_hps:s0_noc_axi4lite_rresp -> agilex_hps:io96b0_to_hps_ch0_axil_rresp
	signal agilex_hps_io96b0_to_hps_axi4_ch0_arlen   : std_logic_vector(7 downto 0);   -- agilex_hps:io96b0_to_hps_axi4_ch0_arlen -> emif_hps:s0_axi4_arlen
	signal agilex_hps_io96b0_to_hps_axi4_ch0_arqos   : std_logic_vector(3 downto 0);   -- agilex_hps:io96b0_to_hps_axi4_ch0_arqos -> emif_hps:s0_axi4_arqos
	signal emif_hps_io96b0_to_hps_axi4_ch0_bresp     : std_logic_vector(1 downto 0);   -- emif_hps:s0_axi4_bresp -> agilex_hps:io96b0_to_hps_axi4_ch0_bresp
	signal emif_hps_io96b0_to_hps_axi4_ch0_clk       : std_logic;                      -- emif_hps:noc_aclk_0 -> agilex_hps:io96b0_to_hps_axi4_ch0_clk
	signal emif_hps_io96b0_to_hps_ch0_axil_reset_n   : std_logic;                      -- emif_hps:s0_noc_axi4lite_reset_n -> agilex_hps:io96b0_to_hps_ch0_axil_reset_n
	signal emif_hps_io96b0_to_hps_ch0_axil_clk       : std_logic;                      -- emif_hps:s0_noc_axi4lite_clock -> agilex_hps:io96b0_to_hps_ch0_axil_clk
	signal emif_hps_io96b0_to_hps_axi4_ch0_rdata     : std_logic_vector(255 downto 0); -- emif_hps:s0_axi4_rdata -> agilex_hps:io96b0_to_hps_axi4_ch0_rdata
	signal agilex_hps_io96b0_to_hps_axi4_ch0_awuser  : std_logic_vector(13 downto 0);  -- agilex_hps:io96b0_to_hps_axi4_ch0_awuser -> emif_hps:s0_axi4_awuser
	signal emif_hps_io96b0_to_hps_axi4_ch0_bvalid    : std_logic;                      -- emif_hps:s0_axi4_bvalid -> agilex_hps:io96b0_to_hps_axi4_ch0_bvalid
	signal emif_hps_io96b0_to_hps_ch0_axil_bvalid    : std_logic;                      -- emif_hps:s0_noc_axi4lite_bvalid -> agilex_hps:io96b0_to_hps_ch0_axil_bvalid
	signal emif_hps_io96b0_to_hps_axi4_ch0_bid       : std_logic_vector(6 downto 0);   -- emif_hps:s0_axi4_bid -> agilex_hps:io96b0_to_hps_axi4_ch0_bid
	signal emif_hps_io96b0_to_hps_ch0_axil_rdata     : std_logic_vector(31 downto 0);  -- emif_hps:s0_noc_axi4lite_rdata -> agilex_hps:io96b0_to_hps_ch0_axil_rdata
	signal agilex_hps_io96b0_to_hps_axi4_ch0_arsize  : std_logic_vector(2 downto 0);   -- agilex_hps:io96b0_to_hps_axi4_ch0_arsize -> emif_hps:s0_axi4_arsize
	signal emif_hps_io96b0_to_hps_axi4_ch0_rlast     : std_logic;                      -- emif_hps:s0_axi4_rlast -> agilex_hps:io96b0_to_hps_axi4_ch0_rlast
	signal emif_hps_io96b0_to_hps_axi4_ch0_rid       : std_logic_vector(6 downto 0);   -- emif_hps:s0_axi4_rid -> agilex_hps:io96b0_to_hps_axi4_ch0_rid
	signal agilex_hps_io96b0_to_hps_ch0_axil_awprot  : std_logic_vector(2 downto 0);   -- agilex_hps:io96b0_to_hps_ch0_axil_awprot -> emif_hps:s0_noc_axi4lite_awprot
	signal agilex_hps_io96b0_to_hps_axi4_ch0_arprot  : std_logic_vector(2 downto 0);   -- agilex_hps:io96b0_to_hps_axi4_ch0_arprot -> emif_hps:s0_axi4_arprot
	signal agilex_hps_io96b0_to_hps_ch0_axil_bready  : std_logic;                      -- agilex_hps:io96b0_to_hps_ch0_axil_bready -> emif_hps:s0_noc_axi4lite_bready
	signal agilex_hps_io96b0_to_hps_ch0_axil_wstrb   : std_logic_vector(3 downto 0);   -- agilex_hps:io96b0_to_hps_ch0_axil_wstrb -> emif_hps:s0_noc_axi4lite_wstrb
	signal emif_hps_io96b0_to_hps_axi4_ch0_rvalid    : std_logic;                      -- emif_hps:s0_axi4_rvalid -> agilex_hps:io96b0_to_hps_axi4_ch0_rvalid
	signal emif_hps_io96b0_to_hps_ch0_axil_awready   : std_logic;                      -- emif_hps:s0_noc_axi4lite_awready -> agilex_hps:io96b0_to_hps_ch0_axil_awready
	signal agilex_hps_io96b0_to_hps_axi4_ch0_wdata   : std_logic_vector(255 downto 0); -- agilex_hps:io96b0_to_hps_axi4_ch0_wdata -> emif_hps:s0_axi4_wdata
	signal emif_hps_io96b0_to_hps_ch0_axil_arready   : std_logic;                      -- emif_hps:s0_noc_axi4lite_arready -> agilex_hps:io96b0_to_hps_ch0_axil_arready
	signal agilex_hps_io96b0_to_hps_axi4_ch0_awburst : std_logic_vector(1 downto 0);   -- agilex_hps:io96b0_to_hps_axi4_ch0_awburst -> emif_hps:s0_axi4_awburst
	signal agilex_hps_io96b0_to_hps_axi4_ch0_araddr  : std_logic_vector(39 downto 0);  -- agilex_hps:io96b0_to_hps_axi4_ch0_araddr -> emif_hps:s0_axi4_araddr
	signal agilex_hps_io96b0_to_hps_axi4_ch0_wvalid  : std_logic;                      -- agilex_hps:io96b0_to_hps_axi4_ch0_wvalid -> emif_hps:s0_axi4_wvalid
	signal agilex_hps_io96b0_to_hps_axi4_ch0_wuser   : std_logic_vector(31 downto 0);  -- agilex_hps:io96b0_to_hps_axi4_ch0_wuser -> emif_hps:s0_axi4_wuser
	signal agilex_hps_io96b0_to_hps_axi4_ch0_wstrb   : std_logic_vector(31 downto 0);  -- agilex_hps:io96b0_to_hps_axi4_ch0_wstrb -> emif_hps:s0_axi4_wstrb
	signal agilex_hps_io96b0_to_hps_ch0_axil_arvalid : std_logic;                      -- agilex_hps:io96b0_to_hps_ch0_axil_arvalid -> emif_hps:s0_noc_axi4lite_arvalid
	signal agilex_hps_io96b0_to_hps_ch0_axil_awaddr  : std_logic_vector(26 downto 0);  -- agilex_hps:io96b0_to_hps_ch0_axil_awaddr -> emif_hps:s0_noc_axi4lite_awaddr
	signal agilex_hps_io96b0_to_hps_axi4_ch0_awlock  : std_logic;                      -- agilex_hps:io96b0_to_hps_axi4_ch0_awlock -> emif_hps:s0_axi4_awlock
	signal agilex_hps_io96b0_to_hps_axi4_ch0_wlast   : std_logic;                      -- agilex_hps:io96b0_to_hps_axi4_ch0_wlast -> emif_hps:s0_axi4_wlast
	signal emif_hps_io96b0_to_hps_axi4_ch0_reset_n   : std_logic;                      -- emif_hps:noc_rst_n_0 -> agilex_hps:io96b0_to_hps_axi4_ch0_reset_n
	signal agilex_hps_io96b0_to_hps_axi4_ch0_awlen   : std_logic_vector(7 downto 0);   -- agilex_hps:io96b0_to_hps_axi4_ch0_awlen -> emif_hps:s0_axi4_awlen
	signal agilex_hps_io96b0_to_hps_axi4_ch0_awqos   : std_logic_vector(3 downto 0);   -- agilex_hps:io96b0_to_hps_axi4_ch0_awqos -> emif_hps:s0_axi4_awqos
	signal emif_hps_io96b0_to_hps_ch0_axil_bresp     : std_logic_vector(1 downto 0);   -- emif_hps:s0_noc_axi4lite_bresp -> agilex_hps:io96b0_to_hps_ch0_axil_bresp
	signal agilex_hps_io96b0_to_hps_axi4_ch0_aruser  : std_logic_vector(13 downto 0);  -- agilex_hps:io96b0_to_hps_axi4_ch0_aruser -> emif_hps:s0_axi4_aruser
	signal agilex_hps_io96b0_to_hps_ch0_axil_rready  : std_logic;                      -- agilex_hps:io96b0_to_hps_ch0_axil_rready -> emif_hps:s0_noc_axi4lite_rready
	signal emif_hps_io96b0_to_hps_axi4_ch0_arready   : std_logic;                      -- emif_hps:s0_axi4_arready -> agilex_hps:io96b0_to_hps_axi4_ch0_arready
	signal agilex_hps_io96b0_to_hps_axi4_ch0_rready  : std_logic;                      -- agilex_hps:io96b0_to_hps_axi4_ch0_rready -> emif_hps:s0_axi4_rready
	signal emif_hps_io96b0_to_hps_axi4_ch0_rresp     : std_logic_vector(1 downto 0);   -- emif_hps:s0_axi4_rresp -> agilex_hps:io96b0_to_hps_axi4_ch0_rresp
	signal agilex_hps_io96b0_to_hps_axi4_ch0_arid    : std_logic_vector(6 downto 0);   -- agilex_hps:io96b0_to_hps_axi4_ch0_arid -> emif_hps:s0_axi4_arid
	signal emif_hps_io96b0_to_hps_ch0_axil_wready    : std_logic;                      -- emif_hps:s0_noc_axi4lite_wready -> agilex_hps:io96b0_to_hps_ch0_axil_wready
	signal emif_hps_io96b0_to_hps_axi4_ch0_ruser     : std_logic_vector(31 downto 0);  -- emif_hps:s0_axi4_ruser -> agilex_hps:io96b0_to_hps_axi4_ch0_ruser
	signal emif_hps_io96b0_to_hps_axi4_ch0_awready   : std_logic;                      -- emif_hps:s0_axi4_awready -> agilex_hps:io96b0_to_hps_axi4_ch0_awready
	signal agilex_hps_io96b0_to_hps_axi4_ch0_arburst : std_logic_vector(1 downto 0);   -- agilex_hps:io96b0_to_hps_axi4_ch0_arburst -> emif_hps:s0_axi4_arburst
	signal emif_hps_io96b0_to_hps_axi4_ch0_wready    : std_logic;                      -- emif_hps:s0_axi4_wready -> agilex_hps:io96b0_to_hps_axi4_ch0_wready
	signal agilex_hps_io96b0_to_hps_axi4_ch0_awsize  : std_logic_vector(2 downto 0);   -- agilex_hps:io96b0_to_hps_axi4_ch0_awsize -> emif_hps:s0_axi4_awsize
	signal agilex_hps_io96b0_to_hps_ch0_axil_awvalid : std_logic;                      -- agilex_hps:io96b0_to_hps_ch0_axil_awvalid -> emif_hps:s0_noc_axi4lite_awvalid
	signal agilex_hps_io96b0_to_hps_ch0_axil_wdata   : std_logic_vector(31 downto 0);  -- agilex_hps:io96b0_to_hps_ch0_axil_wdata -> emif_hps:s0_noc_axi4lite_wdata

	for agilex_hps : agilex_hps_cmp
		use entity agilex_hps.agilex_hps;
	for emif_hps : emif_io96b_hps_cmp
		use entity emif_io96b_hps.emif_io96b_hps;
	for s10_user_rst_clkgate_0 : hps_subsys_s10_user_rst_clkgate_0_cmp
		use entity hps_subsys_s10_user_rst_clkgate_0.hps_subsys_s10_user_rst_clkgate_0;
begin

	agilex_hps : component agilex_hps_cmp
		port map (
			h2f_reset_reset                => h2f_reset_reset,                           --               h2f_reset.reset
			lwhps2fpga_axi_clock_clk       => lwhps2fpga_axi_clock_clk,                  --    lwhps2fpga_axi_clock.clk
			lwhps2fpga_axi_reset_reset     => lwhps2fpga_axi_reset_reset,                --    lwhps2fpga_axi_reset.reset
			lwhps2fpga_awid                => lwhps2fpga_awid,                           --              lwhps2fpga.awid
			lwhps2fpga_awaddr              => lwhps2fpga_awaddr,                         --                        .awaddr
			lwhps2fpga_awlen               => lwhps2fpga_awlen,                          --                        .awlen
			lwhps2fpga_awsize              => lwhps2fpga_awsize,                         --                        .awsize
			lwhps2fpga_awburst             => lwhps2fpga_awburst,                        --                        .awburst
			lwhps2fpga_awlock              => lwhps2fpga_awlock,                         --                        .awlock
			lwhps2fpga_awcache             => lwhps2fpga_awcache,                        --                        .awcache
			lwhps2fpga_awprot              => lwhps2fpga_awprot,                         --                        .awprot
			lwhps2fpga_awvalid             => lwhps2fpga_awvalid,                        --                        .awvalid
			lwhps2fpga_awready             => lwhps2fpga_awready,                        --                        .awready
			lwhps2fpga_wdata               => lwhps2fpga_wdata,                          --                        .wdata
			lwhps2fpga_wstrb               => lwhps2fpga_wstrb,                          --                        .wstrb
			lwhps2fpga_wlast               => lwhps2fpga_wlast,                          --                        .wlast
			lwhps2fpga_wvalid              => lwhps2fpga_wvalid,                         --                        .wvalid
			lwhps2fpga_wready              => lwhps2fpga_wready,                         --                        .wready
			lwhps2fpga_bid                 => lwhps2fpga_bid,                            --                        .bid
			lwhps2fpga_bresp               => lwhps2fpga_bresp,                          --                        .bresp
			lwhps2fpga_bvalid              => lwhps2fpga_bvalid,                         --                        .bvalid
			lwhps2fpga_bready              => lwhps2fpga_bready,                         --                        .bready
			lwhps2fpga_arid                => lwhps2fpga_arid,                           --                        .arid
			lwhps2fpga_araddr              => lwhps2fpga_araddr,                         --                        .araddr
			lwhps2fpga_arlen               => lwhps2fpga_arlen,                          --                        .arlen
			lwhps2fpga_arsize              => lwhps2fpga_arsize,                         --                        .arsize
			lwhps2fpga_arburst             => lwhps2fpga_arburst,                        --                        .arburst
			lwhps2fpga_arlock              => lwhps2fpga_arlock,                         --                        .arlock
			lwhps2fpga_arcache             => lwhps2fpga_arcache,                        --                        .arcache
			lwhps2fpga_arprot              => lwhps2fpga_arprot,                         --                        .arprot
			lwhps2fpga_arvalid             => lwhps2fpga_arvalid,                        --                        .arvalid
			lwhps2fpga_arready             => lwhps2fpga_arready,                        --                        .arready
			lwhps2fpga_rid                 => lwhps2fpga_rid,                            --                        .rid
			lwhps2fpga_rdata               => lwhps2fpga_rdata,                          --                        .rdata
			lwhps2fpga_rresp               => lwhps2fpga_rresp,                          --                        .rresp
			lwhps2fpga_rlast               => lwhps2fpga_rlast,                          --                        .rlast
			lwhps2fpga_rvalid              => lwhps2fpga_rvalid,                         --                        .rvalid
			lwhps2fpga_rready              => lwhps2fpga_rready,                         --                        .rready
			emac0_app_rst_reset_n          => open,                                      --           emac0_app_rst.reset_n
			uart0_cts_n                    => hps_uart0_cts_n,                           --                   uart0.cts_n
			uart0_dcd_n                    => hps_uart0_dcd_n,                           --                        .dcd_n
			uart0_dsr_n                    => hps_uart0_dsr_n,                           --                        .dsr_n
			uart0_dtr_n                    => hps_uart0_dtr_n,                           --                        .dtr_n
			uart0_out1_n                   => hps_uart0_out1_n,                          --                        .out1_n
			uart0_out2_n                   => hps_uart0_out2_n,                          --                        .out2_n
			uart0_ri_n                     => hps_uart0_ri_n,                            --                        .ri_n
			uart0_rts_n                    => hps_uart0_rts_n,                           --                        .rts_n
			uart0_rx                       => hps_uart0_rx,                              --                        .rx
			uart0_tx                       => hps_uart0_tx,                              --                        .tx
			hps_io_hps_osc_clk             => hps_io_hps_osc_clk,                        --                  hps_io.hps_osc_clk
			hps_io_sdmmc_data0             => hps_io_sdmmc_data0,                        --                        .sdmmc_data0
			hps_io_sdmmc_data1             => hps_io_sdmmc_data1,                        --                        .sdmmc_data1
			hps_io_sdmmc_cclk              => hps_io_sdmmc_cclk,                         --                        .sdmmc_cclk
			hps_io_sdmmc_data2             => hps_io_sdmmc_data2,                        --                        .sdmmc_data2
			hps_io_sdmmc_data3             => hps_io_sdmmc_data3,                        --                        .sdmmc_data3
			hps_io_sdmmc_cmd               => hps_io_sdmmc_cmd,                          --                        .sdmmc_cmd
			hps_io_emac0_tx_clk            => hps_io_emac0_tx_clk,                       --                        .emac0_tx_clk
			hps_io_emac0_tx_ctl            => hps_io_emac0_tx_ctl,                       --                        .emac0_tx_ctl
			hps_io_emac0_rx_clk            => hps_io_emac0_rx_clk,                       --                        .emac0_rx_clk
			hps_io_emac0_rx_ctl            => hps_io_emac0_rx_ctl,                       --                        .emac0_rx_ctl
			hps_io_emac0_txd0              => hps_io_emac0_txd0,                         --                        .emac0_txd0
			hps_io_emac0_txd1              => hps_io_emac0_txd1,                         --                        .emac0_txd1
			hps_io_emac0_rxd0              => hps_io_emac0_rxd0,                         --                        .emac0_rxd0
			hps_io_emac0_rxd1              => hps_io_emac0_rxd1,                         --                        .emac0_rxd1
			hps_io_emac0_txd2              => hps_io_emac0_txd2,                         --                        .emac0_txd2
			hps_io_emac0_txd3              => hps_io_emac0_txd3,                         --                        .emac0_txd3
			hps_io_emac0_rxd2              => hps_io_emac0_rxd2,                         --                        .emac0_rxd2
			hps_io_emac0_rxd3              => hps_io_emac0_rxd3,                         --                        .emac0_rxd3
			hps_io_mdio0_mdio              => hps_io_mdio0_mdio,                         --                        .mdio0_mdio
			hps_io_mdio0_mdc               => hps_io_mdio0_mdc,                          --                        .mdio0_mdc
			hps_io_uart1_tx                => hps_io_uart1_tx,                           --                        .uart1_tx
			hps_io_uart1_rx                => hps_io_uart1_rx,                           --                        .uart1_rx
			hps_io_gpio40                  => hps_io_gpio40,                             --                        .gpio40
			hps_io_gpio41                  => hps_io_gpio41,                             --                        .gpio41
			fpga2hps_interrupt_irq1_irq    => f2h_irq1_in_irq,                           -- fpga2hps_interrupt_irq1.irq
			fpga2hps_interrupt_irq0_irq    => f2h_irq0_in_irq,                           -- fpga2hps_interrupt_irq0.irq
			io96b0_to_hps_ch0_axil_clk     => emif_hps_io96b0_to_hps_ch0_axil_clk,       --           io96b0_to_hps.ch0_axil_clk
			io96b0_to_hps_ch0_axil_reset_n => emif_hps_io96b0_to_hps_ch0_axil_reset_n,   --                        .ch0_axil_reset_n
			io96b0_to_hps_ch0_axil_arready => emif_hps_io96b0_to_hps_ch0_axil_arready,   --                        .ch0_axil_arready
			io96b0_to_hps_ch0_axil_awready => emif_hps_io96b0_to_hps_ch0_axil_awready,   --                        .ch0_axil_awready
			io96b0_to_hps_ch0_axil_bresp   => emif_hps_io96b0_to_hps_ch0_axil_bresp,     --                        .ch0_axil_bresp
			io96b0_to_hps_ch0_axil_bvalid  => emif_hps_io96b0_to_hps_ch0_axil_bvalid,    --                        .ch0_axil_bvalid
			io96b0_to_hps_ch0_axil_rdata   => emif_hps_io96b0_to_hps_ch0_axil_rdata,     --                        .ch0_axil_rdata
			io96b0_to_hps_ch0_axil_rresp   => emif_hps_io96b0_to_hps_ch0_axil_rresp,     --                        .ch0_axil_rresp
			io96b0_to_hps_ch0_axil_rvalid  => emif_hps_io96b0_to_hps_ch0_axil_rvalid,    --                        .ch0_axil_rvalid
			io96b0_to_hps_ch0_axil_wready  => emif_hps_io96b0_to_hps_ch0_axil_wready,    --                        .ch0_axil_wready
			io96b0_to_hps_ch0_axil_araddr  => agilex_hps_io96b0_to_hps_ch0_axil_araddr,  --                        .ch0_axil_araddr
			io96b0_to_hps_ch0_axil_arvalid => agilex_hps_io96b0_to_hps_ch0_axil_arvalid, --                        .ch0_axil_arvalid
			io96b0_to_hps_ch0_axil_awaddr  => agilex_hps_io96b0_to_hps_ch0_axil_awaddr,  --                        .ch0_axil_awaddr
			io96b0_to_hps_ch0_axil_awvalid => agilex_hps_io96b0_to_hps_ch0_axil_awvalid, --                        .ch0_axil_awvalid
			io96b0_to_hps_ch0_axil_bready  => agilex_hps_io96b0_to_hps_ch0_axil_bready,  --                        .ch0_axil_bready
			io96b0_to_hps_ch0_axil_rready  => agilex_hps_io96b0_to_hps_ch0_axil_rready,  --                        .ch0_axil_rready
			io96b0_to_hps_ch0_axil_wdata   => agilex_hps_io96b0_to_hps_ch0_axil_wdata,   --                        .ch0_axil_wdata
			io96b0_to_hps_ch0_axil_wstrb   => agilex_hps_io96b0_to_hps_ch0_axil_wstrb,   --                        .ch0_axil_wstrb
			io96b0_to_hps_ch0_axil_wvalid  => agilex_hps_io96b0_to_hps_ch0_axil_wvalid,  --                        .ch0_axil_wvalid
			io96b0_to_hps_ch0_axil_arprot  => agilex_hps_io96b0_to_hps_ch0_axil_arprot,  --                        .ch0_axil_arprot
			io96b0_to_hps_ch0_axil_awprot  => agilex_hps_io96b0_to_hps_ch0_axil_awprot,  --                        .ch0_axil_awprot
			io96b0_to_hps_axi4_ch0_clk     => emif_hps_io96b0_to_hps_axi4_ch0_clk,       --                        .axi4_ch0_clk
			io96b0_to_hps_axi4_ch0_reset_n => emif_hps_io96b0_to_hps_axi4_ch0_reset_n,   --                        .axi4_ch0_reset_n
			io96b0_to_hps_axi4_ch0_arready => emif_hps_io96b0_to_hps_axi4_ch0_arready,   --                        .axi4_ch0_arready
			io96b0_to_hps_axi4_ch0_awready => emif_hps_io96b0_to_hps_axi4_ch0_awready,   --                        .axi4_ch0_awready
			io96b0_to_hps_axi4_ch0_bid     => emif_hps_io96b0_to_hps_axi4_ch0_bid,       --                        .axi4_ch0_bid
			io96b0_to_hps_axi4_ch0_bresp   => emif_hps_io96b0_to_hps_axi4_ch0_bresp,     --                        .axi4_ch0_bresp
			io96b0_to_hps_axi4_ch0_bvalid  => emif_hps_io96b0_to_hps_axi4_ch0_bvalid,    --                        .axi4_ch0_bvalid
			io96b0_to_hps_axi4_ch0_rdata   => emif_hps_io96b0_to_hps_axi4_ch0_rdata,     --                        .axi4_ch0_rdata
			io96b0_to_hps_axi4_ch0_rid     => emif_hps_io96b0_to_hps_axi4_ch0_rid,       --                        .axi4_ch0_rid
			io96b0_to_hps_axi4_ch0_rlast   => emif_hps_io96b0_to_hps_axi4_ch0_rlast,     --                        .axi4_ch0_rlast
			io96b0_to_hps_axi4_ch0_rresp   => emif_hps_io96b0_to_hps_axi4_ch0_rresp,     --                        .axi4_ch0_rresp
			io96b0_to_hps_axi4_ch0_ruser   => emif_hps_io96b0_to_hps_axi4_ch0_ruser,     --                        .axi4_ch0_ruser
			io96b0_to_hps_axi4_ch0_rvalid  => emif_hps_io96b0_to_hps_axi4_ch0_rvalid,    --                        .axi4_ch0_rvalid
			io96b0_to_hps_axi4_ch0_wready  => emif_hps_io96b0_to_hps_axi4_ch0_wready,    --                        .axi4_ch0_wready
			io96b0_to_hps_axi4_ch0_araddr  => agilex_hps_io96b0_to_hps_axi4_ch0_araddr,  --                        .axi4_ch0_araddr
			io96b0_to_hps_axi4_ch0_arburst => agilex_hps_io96b0_to_hps_axi4_ch0_arburst, --                        .axi4_ch0_arburst
			io96b0_to_hps_axi4_ch0_arid    => agilex_hps_io96b0_to_hps_axi4_ch0_arid,    --                        .axi4_ch0_arid
			io96b0_to_hps_axi4_ch0_arlen   => agilex_hps_io96b0_to_hps_axi4_ch0_arlen,   --                        .axi4_ch0_arlen
			io96b0_to_hps_axi4_ch0_arlock  => agilex_hps_io96b0_to_hps_axi4_ch0_arlock,  --                        .axi4_ch0_arlock
			io96b0_to_hps_axi4_ch0_arqos   => agilex_hps_io96b0_to_hps_axi4_ch0_arqos,   --                        .axi4_ch0_arqos
			io96b0_to_hps_axi4_ch0_arsize  => agilex_hps_io96b0_to_hps_axi4_ch0_arsize,  --                        .axi4_ch0_arsize
			io96b0_to_hps_axi4_ch0_aruser  => agilex_hps_io96b0_to_hps_axi4_ch0_aruser,  --                        .axi4_ch0_aruser
			io96b0_to_hps_axi4_ch0_arvalid => agilex_hps_io96b0_to_hps_axi4_ch0_arvalid, --                        .axi4_ch0_arvalid
			io96b0_to_hps_axi4_ch0_awaddr  => agilex_hps_io96b0_to_hps_axi4_ch0_awaddr,  --                        .axi4_ch0_awaddr
			io96b0_to_hps_axi4_ch0_awburst => agilex_hps_io96b0_to_hps_axi4_ch0_awburst, --                        .axi4_ch0_awburst
			io96b0_to_hps_axi4_ch0_awid    => agilex_hps_io96b0_to_hps_axi4_ch0_awid,    --                        .axi4_ch0_awid
			io96b0_to_hps_axi4_ch0_awlen   => agilex_hps_io96b0_to_hps_axi4_ch0_awlen,   --                        .axi4_ch0_awlen
			io96b0_to_hps_axi4_ch0_awlock  => agilex_hps_io96b0_to_hps_axi4_ch0_awlock,  --                        .axi4_ch0_awlock
			io96b0_to_hps_axi4_ch0_awqos   => agilex_hps_io96b0_to_hps_axi4_ch0_awqos,   --                        .axi4_ch0_awqos
			io96b0_to_hps_axi4_ch0_awsize  => agilex_hps_io96b0_to_hps_axi4_ch0_awsize,  --                        .axi4_ch0_awsize
			io96b0_to_hps_axi4_ch0_awuser  => agilex_hps_io96b0_to_hps_axi4_ch0_awuser,  --                        .axi4_ch0_awuser
			io96b0_to_hps_axi4_ch0_awvalid => agilex_hps_io96b0_to_hps_axi4_ch0_awvalid, --                        .axi4_ch0_awvalid
			io96b0_to_hps_axi4_ch0_bready  => agilex_hps_io96b0_to_hps_axi4_ch0_bready,  --                        .axi4_ch0_bready
			io96b0_to_hps_axi4_ch0_rready  => agilex_hps_io96b0_to_hps_axi4_ch0_rready,  --                        .axi4_ch0_rready
			io96b0_to_hps_axi4_ch0_wdata   => agilex_hps_io96b0_to_hps_axi4_ch0_wdata,   --                        .axi4_ch0_wdata
			io96b0_to_hps_axi4_ch0_wlast   => agilex_hps_io96b0_to_hps_axi4_ch0_wlast,   --                        .axi4_ch0_wlast
			io96b0_to_hps_axi4_ch0_wstrb   => agilex_hps_io96b0_to_hps_axi4_ch0_wstrb,   --                        .axi4_ch0_wstrb
			io96b0_to_hps_axi4_ch0_wuser   => agilex_hps_io96b0_to_hps_axi4_ch0_wuser,   --                        .axi4_ch0_wuser
			io96b0_to_hps_axi4_ch0_wvalid  => agilex_hps_io96b0_to_hps_axi4_ch0_wvalid,  --                        .axi4_ch0_wvalid
			io96b0_to_hps_axi4_ch0_arprot  => agilex_hps_io96b0_to_hps_axi4_ch0_arprot,  --                        .axi4_ch0_arprot
			io96b0_to_hps_axi4_ch0_awprot  => agilex_hps_io96b0_to_hps_axi4_ch0_awprot   --                        .axi4_ch0_awprot
		);

	emif_hps : component emif_io96b_hps_cmp
		port map (
			s0_noc_axi4lite_clock   => emif_hps_io96b0_to_hps_ch0_axil_clk,       -- io96b0_to_hps.ch0_axil_clk
			s0_noc_axi4lite_reset_n => emif_hps_io96b0_to_hps_ch0_axil_reset_n,   --              .ch0_axil_reset_n
			s0_noc_axi4lite_awaddr  => agilex_hps_io96b0_to_hps_ch0_axil_awaddr,  --              .ch0_axil_awaddr
			s0_noc_axi4lite_awvalid => agilex_hps_io96b0_to_hps_ch0_axil_awvalid, --              .ch0_axil_awvalid
			s0_noc_axi4lite_awready => emif_hps_io96b0_to_hps_ch0_axil_awready,   --              .ch0_axil_awready
			s0_noc_axi4lite_araddr  => agilex_hps_io96b0_to_hps_ch0_axil_araddr,  --              .ch0_axil_araddr
			s0_noc_axi4lite_arvalid => agilex_hps_io96b0_to_hps_ch0_axil_arvalid, --              .ch0_axil_arvalid
			s0_noc_axi4lite_arready => emif_hps_io96b0_to_hps_ch0_axil_arready,   --              .ch0_axil_arready
			s0_noc_axi4lite_wdata   => agilex_hps_io96b0_to_hps_ch0_axil_wdata,   --              .ch0_axil_wdata
			s0_noc_axi4lite_wvalid  => agilex_hps_io96b0_to_hps_ch0_axil_wvalid,  --              .ch0_axil_wvalid
			s0_noc_axi4lite_wready  => emif_hps_io96b0_to_hps_ch0_axil_wready,    --              .ch0_axil_wready
			s0_noc_axi4lite_rresp   => emif_hps_io96b0_to_hps_ch0_axil_rresp,     --              .ch0_axil_rresp
			s0_noc_axi4lite_rdata   => emif_hps_io96b0_to_hps_ch0_axil_rdata,     --              .ch0_axil_rdata
			s0_noc_axi4lite_rvalid  => emif_hps_io96b0_to_hps_ch0_axil_rvalid,    --              .ch0_axil_rvalid
			s0_noc_axi4lite_rready  => agilex_hps_io96b0_to_hps_ch0_axil_rready,  --              .ch0_axil_rready
			s0_noc_axi4lite_bresp   => emif_hps_io96b0_to_hps_ch0_axil_bresp,     --              .ch0_axil_bresp
			s0_noc_axi4lite_bvalid  => emif_hps_io96b0_to_hps_ch0_axil_bvalid,    --              .ch0_axil_bvalid
			s0_noc_axi4lite_bready  => agilex_hps_io96b0_to_hps_ch0_axil_bready,  --              .ch0_axil_bready
			s0_noc_axi4lite_awprot  => agilex_hps_io96b0_to_hps_ch0_axil_awprot,  --              .ch0_axil_awprot
			s0_noc_axi4lite_arprot  => agilex_hps_io96b0_to_hps_ch0_axil_arprot,  --              .ch0_axil_arprot
			s0_noc_axi4lite_wstrb   => agilex_hps_io96b0_to_hps_ch0_axil_wstrb,   --              .ch0_axil_wstrb
			s0_axi4_awaddr          => agilex_hps_io96b0_to_hps_axi4_ch0_awaddr,  --              .axi4_ch0_awaddr
			s0_axi4_awburst         => agilex_hps_io96b0_to_hps_axi4_ch0_awburst, --              .axi4_ch0_awburst
			s0_axi4_awid            => agilex_hps_io96b0_to_hps_axi4_ch0_awid,    --              .axi4_ch0_awid
			s0_axi4_awlen           => agilex_hps_io96b0_to_hps_axi4_ch0_awlen,   --              .axi4_ch0_awlen
			s0_axi4_awlock          => agilex_hps_io96b0_to_hps_axi4_ch0_awlock,  --              .axi4_ch0_awlock
			s0_axi4_awqos           => agilex_hps_io96b0_to_hps_axi4_ch0_awqos,   --              .axi4_ch0_awqos
			s0_axi4_awsize          => agilex_hps_io96b0_to_hps_axi4_ch0_awsize,  --              .axi4_ch0_awsize
			s0_axi4_awvalid         => agilex_hps_io96b0_to_hps_axi4_ch0_awvalid, --              .axi4_ch0_awvalid
			s0_axi4_awuser          => agilex_hps_io96b0_to_hps_axi4_ch0_awuser,  --              .axi4_ch0_awuser
			s0_axi4_awprot          => agilex_hps_io96b0_to_hps_axi4_ch0_awprot,  --              .axi4_ch0_awprot
			s0_axi4_awready         => emif_hps_io96b0_to_hps_axi4_ch0_awready,   --              .axi4_ch0_awready
			s0_axi4_araddr          => agilex_hps_io96b0_to_hps_axi4_ch0_araddr,  --              .axi4_ch0_araddr
			s0_axi4_arburst         => agilex_hps_io96b0_to_hps_axi4_ch0_arburst, --              .axi4_ch0_arburst
			s0_axi4_arid            => agilex_hps_io96b0_to_hps_axi4_ch0_arid,    --              .axi4_ch0_arid
			s0_axi4_arlen           => agilex_hps_io96b0_to_hps_axi4_ch0_arlen,   --              .axi4_ch0_arlen
			s0_axi4_arlock          => agilex_hps_io96b0_to_hps_axi4_ch0_arlock,  --              .axi4_ch0_arlock
			s0_axi4_arqos           => agilex_hps_io96b0_to_hps_axi4_ch0_arqos,   --              .axi4_ch0_arqos
			s0_axi4_arsize          => agilex_hps_io96b0_to_hps_axi4_ch0_arsize,  --              .axi4_ch0_arsize
			s0_axi4_arvalid         => agilex_hps_io96b0_to_hps_axi4_ch0_arvalid, --              .axi4_ch0_arvalid
			s0_axi4_aruser          => agilex_hps_io96b0_to_hps_axi4_ch0_aruser,  --              .axi4_ch0_aruser
			s0_axi4_arprot          => agilex_hps_io96b0_to_hps_axi4_ch0_arprot,  --              .axi4_ch0_arprot
			s0_axi4_arready         => emif_hps_io96b0_to_hps_axi4_ch0_arready,   --              .axi4_ch0_arready
			s0_axi4_wdata           => agilex_hps_io96b0_to_hps_axi4_ch0_wdata,   --              .axi4_ch0_wdata
			s0_axi4_wstrb           => agilex_hps_io96b0_to_hps_axi4_ch0_wstrb,   --              .axi4_ch0_wstrb
			s0_axi4_wlast           => agilex_hps_io96b0_to_hps_axi4_ch0_wlast,   --              .axi4_ch0_wlast
			s0_axi4_wvalid          => agilex_hps_io96b0_to_hps_axi4_ch0_wvalid,  --              .axi4_ch0_wvalid
			s0_axi4_wready          => emif_hps_io96b0_to_hps_axi4_ch0_wready,    --              .axi4_ch0_wready
			s0_axi4_bready          => agilex_hps_io96b0_to_hps_axi4_ch0_bready,  --              .axi4_ch0_bready
			s0_axi4_bid             => emif_hps_io96b0_to_hps_axi4_ch0_bid,       --              .axi4_ch0_bid
			s0_axi4_bresp           => emif_hps_io96b0_to_hps_axi4_ch0_bresp,     --              .axi4_ch0_bresp
			s0_axi4_bvalid          => emif_hps_io96b0_to_hps_axi4_ch0_bvalid,    --              .axi4_ch0_bvalid
			s0_axi4_rready          => agilex_hps_io96b0_to_hps_axi4_ch0_rready,  --              .axi4_ch0_rready
			s0_axi4_rdata           => emif_hps_io96b0_to_hps_axi4_ch0_rdata,     --              .axi4_ch0_rdata
			s0_axi4_rid             => emif_hps_io96b0_to_hps_axi4_ch0_rid,       --              .axi4_ch0_rid
			s0_axi4_rlast           => emif_hps_io96b0_to_hps_axi4_ch0_rlast,     --              .axi4_ch0_rlast
			s0_axi4_rresp           => emif_hps_io96b0_to_hps_axi4_ch0_rresp,     --              .axi4_ch0_rresp
			s0_axi4_rvalid          => emif_hps_io96b0_to_hps_axi4_ch0_rvalid,    --              .axi4_ch0_rvalid
			noc_aclk_0              => emif_hps_io96b0_to_hps_axi4_ch0_clk,       --              .axi4_ch0_clk
			noc_rst_n_0             => emif_hps_io96b0_to_hps_axi4_ch0_reset_n,   --              .axi4_ch0_reset_n
			s0_axi4_wuser           => agilex_hps_io96b0_to_hps_axi4_ch0_wuser,   --              .axi4_ch0_wuser
			s0_axi4_ruser           => emif_hps_io96b0_to_hps_axi4_ch0_ruser,     --              .axi4_ch0_ruser
			mem_0_cs                => emif_hps_emif_mem_0_mem_cs,                --         mem_0.mem_cs
			mem_0_ca                => emif_hps_emif_mem_0_mem_ca,                --              .mem_ca
			mem_0_cke               => emif_hps_emif_mem_0_mem_cke,               --              .mem_cke
			mem_0_dq                => emif_hps_emif_mem_0_mem_dq,                --              .mem_dq
			mem_0_dqs_t             => emif_hps_emif_mem_0_mem_dqs_t,             --              .mem_dqs_t
			mem_0_dqs_c             => emif_hps_emif_mem_0_mem_dqs_c,             --              .mem_dqs_c
			mem_0_dmi               => emif_hps_emif_mem_0_mem_dmi,               --              .mem_dmi
			mem_0_ck_t              => emif_hps_emif_mem_ck_0_mem_ck_t,           --      mem_ck_0.mem_ck_t
			mem_0_ck_c              => emif_hps_emif_mem_ck_0_mem_ck_c,           --              .mem_ck_c
			mem_0_reset_n           => emif_hps_emif_mem_reset_n_mem_reset_n,     --   mem_reset_n.mem_reset_n
			oct_rzqin_0             => emif_hps_emif_oct_0_oct_rzqin,             --         oct_0.oct_rzqin
			ref_clk                 => emif_hps_emif_ref_clk_clk                  --       ref_clk.clk
		);

	s10_user_rst_clkgate_0 : component hps_subsys_s10_user_rst_clkgate_0_cmp
		port map (
			ninit_done => ninit_done_reset  -- ninit_done.reset
		);

end architecture rtl; -- of hps_subsys
