-- agilex_hps.vhd

-- Generated using ACDS version 26.1.1 130

library IEEE;
library intel_agilex_5_soc_1400;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity agilex_hps is
	port (
		h2f_reset_reset                : out   std_logic;                                         --               h2f_reset.reset,            Active high reset from the HPS Reset Manager.
		lwhps2fpga_axi_clock_clk       : in    std_logic                      := '0';             --    lwhps2fpga_axi_clock.clk,              clock from a single source in the FPGA.
		lwhps2fpga_axi_reset_reset     : in    std_logic                      := '0';             --    lwhps2fpga_axi_reset.reset,            Async reset to the Bridge logic. This signal is active-HIGH.
		lwhps2fpga_awid                : out   std_logic_vector(3 downto 0);                      --              lwhps2fpga.awid,             Identification tag for a write transaction.
		lwhps2fpga_awaddr              : out   std_logic_vector(28 downto 0);                     --                        .awaddr,           The address of the first transfer in a write transaction.
		lwhps2fpga_awlen               : out   std_logic_vector(7 downto 0);                      --                        .awlen,            The exact number of data transfers in a write transaction.
		lwhps2fpga_awsize              : out   std_logic_vector(2 downto 0);                      --                        .awsize,           The number of bytes in each data transfer in a write transaction.
		lwhps2fpga_awburst             : out   std_logic_vector(1 downto 0);                      --                        .awburst,          Indicates how address changes between each transfer in a write transaction.
		lwhps2fpga_awlock              : out   std_logic;                                         --                        .awlock,           Provides information about the atomic characteristics of a write transaction.
		lwhps2fpga_awcache             : out   std_logic_vector(3 downto 0);                      --                        .awcache,          Indicates how a write transaction is required to progress through a system.
		lwhps2fpga_awprot              : out   std_logic_vector(2 downto 0);                      --                        .awprot,           Protection attributes of a write transaction: privilege, security level, and access type.
		lwhps2fpga_awvalid             : out   std_logic;                                         --                        .awvalid,          Indicates that the write address channel signals are valid.
		lwhps2fpga_awready             : in    std_logic                      := '0';             --                        .awready,          Indicates that a transfer on the write address channel can be accepted.
		lwhps2fpga_wdata               : out   std_logic_vector(31 downto 0);                     --                        .wdata,            Write data.
		lwhps2fpga_wstrb               : out   std_logic_vector(3 downto 0);                      --                        .wstrb,            Write strobes, indicate which byte lanes hold valid data.
		lwhps2fpga_wlast               : out   std_logic;                                         --                        .wlast,            User-defined extension for the write data channel.
		lwhps2fpga_wvalid              : out   std_logic;                                         --                        .wvalid,           Indicates that the write data channel signals are valid.
		lwhps2fpga_wready              : in    std_logic                      := '0';             --                        .wready,           Indicates that a transfer on the write data channel can be accepted.
		lwhps2fpga_bid                 : in    std_logic_vector(3 downto 0)   := (others => '0'); --                        .bid,              Transaction identifier for the write response.
		lwhps2fpga_bresp               : in    std_logic_vector(1 downto 0)   := (others => '0'); --                        .bresp,            Write response, indicates the status of a write transaction.
		lwhps2fpga_bvalid              : in    std_logic                      := '0';             --                        .bvalid,           Indicates that the write response channel signals are valid.
		lwhps2fpga_bready              : out   std_logic;                                         --                        .bready,           Indicates that a transfer on the write response channel can be accepted.
		lwhps2fpga_arid                : out   std_logic_vector(3 downto 0);                      --                        .arid,             Transaction identifier for the read transaction.
		lwhps2fpga_araddr              : out   std_logic_vector(28 downto 0);                     --                        .araddr,           The address of the first transfer in a read transaction.
		lwhps2fpga_arlen               : out   std_logic_vector(7 downto 0);                      --                        .arlen,            The exact number of data transfers in a read transaction.
		lwhps2fpga_arsize              : out   std_logic_vector(2 downto 0);                      --                        .arsize,           The number of bytes in each data transfer in a read transaction.
		lwhps2fpga_arburst             : out   std_logic_vector(1 downto 0);                      --                        .arburst,          Indicates how address changes between each transfer in a read transaction.
		lwhps2fpga_arlock              : out   std_logic;                                         --                        .arlock,           Provides information about the atomic characteristics of a read transaction.
		lwhps2fpga_arcache             : out   std_logic_vector(3 downto 0);                      --                        .arcache,          Indicates how a read transaction is required to progress through a system.
		lwhps2fpga_arprot              : out   std_logic_vector(2 downto 0);                      --                        .arprot,           Protection attributes of a read transaction: privilege, security level, and access type.
		lwhps2fpga_arvalid             : out   std_logic;                                         --                        .arvalid,          Indicates that the read address channel signals are valid.
		lwhps2fpga_arready             : in    std_logic                      := '0';             --                        .arready,          Indicates that a transfer on the read address channel can be accepted.
		lwhps2fpga_rid                 : in    std_logic_vector(3 downto 0)   := (others => '0'); --                        .rid,              Identification tag for read data and response.
		lwhps2fpga_rdata               : in    std_logic_vector(31 downto 0)  := (others => '0'); --                        .rdata,            Read data.
		lwhps2fpga_rresp               : in    std_logic_vector(1 downto 0)   := (others => '0'); --                        .rresp,            Read response, indicates the status of a read transfer.
		lwhps2fpga_rlast               : in    std_logic                      := '0';             --                        .rlast,            Indicates whether this is the last data transfer in a read transaction.
		lwhps2fpga_rvalid              : in    std_logic                      := '0';             --                        .rvalid,           Indicates that the read data channel signals are valid.
		lwhps2fpga_rready              : out   std_logic;                                         --                        .rready,           Indicates that a transfer on the read data channel can be accepted.
		emac0_app_rst_reset_n          : out   std_logic;                                         --           emac0_app_rst.reset_n,          EMAC0 application clock reset output.
		uart0_cts_n                    : in    std_logic                      := '0';             --                   uart0.cts_n,            Clear to send. Necessary for auto flow control feature.
		uart0_dcd_n                    : in    std_logic                      := '0';             --                        .dcd_n,            Data carrier detect.
		uart0_dsr_n                    : in    std_logic                      := '0';             --                        .dsr_n,            Data set ready.
		uart0_dtr_n                    : out   std_logic;                                         --                        .dtr_n,            Data terminal ready.
		uart0_out1_n                   : out   std_logic;                                         --                        .out1_n,           User defined output 1.
		uart0_out2_n                   : out   std_logic;                                         --                        .out2_n,           User defined output 2.
		uart0_ri_n                     : in    std_logic                      := '0';             --                        .ri_n,             Ring indicator.
		uart0_rts_n                    : out   std_logic;                                         --                        .rts_n,            Request to send. Necessary for auto flow control feature.
		uart0_rx                       : in    std_logic                      := '0';             --                        .rx,               Receive data.
		uart0_tx                       : out   std_logic;                                         --                        .tx,               Transmit data.
		hps_io_hps_osc_clk             : in    std_logic                      := '0';             --                  hps_io.hps_osc_clk,      HPS input clock pin for EOSC reference clock.
		hps_io_sdmmc_data0             : inout std_logic                      := '0';             --                        .sdmmc_data0,      SDMMC data[0].
		hps_io_sdmmc_data1             : inout std_logic                      := '0';             --                        .sdmmc_data1,      SDMMC data[1].
		hps_io_sdmmc_cclk              : out   std_logic;                                         --                        .sdmmc_cclk,       SDMMC output clock.
		hps_io_sdmmc_data2             : inout std_logic                      := '0';             --                        .sdmmc_data2,      SDMMC data[2].
		hps_io_sdmmc_data3             : inout std_logic                      := '0';             --                        .sdmmc_data3,      SDMMC data[3].
		hps_io_sdmmc_cmd               : inout std_logic                      := '0';             --                        .sdmmc_cmd,        SDMMC command.
		hps_io_emac0_tx_clk            : out   std_logic;                                         --                        .emac0_tx_clk,     EMAC0 transmit clock.
		hps_io_emac0_tx_ctl            : out   std_logic;                                         --                        .emac0_tx_ctl,     EMAC0 transmit data enable.
		hps_io_emac0_rx_clk            : in    std_logic                      := '0';             --                        .emac0_rx_clk,     EMAC0 receive clock.
		hps_io_emac0_rx_ctl            : in    std_logic                      := '0';             --                        .emac0_rx_ctl,     EMAC0 receive data enable.
		hps_io_emac0_txd0              : out   std_logic;                                         --                        .emac0_txd0,       EMAC0 transmit data[0].
		hps_io_emac0_txd1              : out   std_logic;                                         --                        .emac0_txd1,       EMAC0 transmit data[1].
		hps_io_emac0_rxd0              : in    std_logic                      := '0';             --                        .emac0_rxd0,       EMAC0 receive data[0].
		hps_io_emac0_rxd1              : in    std_logic                      := '0';             --                        .emac0_rxd1,       EMAC0 receive data[1].
		hps_io_emac0_txd2              : out   std_logic;                                         --                        .emac0_txd2,       EMAC0 transmit data[2].
		hps_io_emac0_txd3              : out   std_logic;                                         --                        .emac0_txd3,       EMAC0 transmit data[3].
		hps_io_emac0_rxd2              : in    std_logic                      := '0';             --                        .emac0_rxd2,       EMAC0 receive data[2].
		hps_io_emac0_rxd3              : in    std_logic                      := '0';             --                        .emac0_rxd3,       EMAC0 receive data[3].
		hps_io_mdio0_mdio              : inout std_logic                      := '0';             --                        .mdio0_mdio,       EMAC0 MDIO data.
		hps_io_mdio0_mdc               : out   std_logic;                                         --                        .mdio0_mdc,        EMAC0 MDIO clock.
		hps_io_uart1_tx                : out   std_logic;                                         --                        .uart1_tx,         UART1 transmit data.
		hps_io_uart1_rx                : in    std_logic                      := '0';             --                        .uart1_rx,         UART1 receive data.
		hps_io_gpio40                  : inout std_logic                      := '0';             --                        .gpio40,           GPIO1 IO16
		hps_io_gpio41                  : inout std_logic                      := '0';             --                        .gpio41,           GPIO1 IO17
		fpga2hps_interrupt_irq1_irq    : in    std_logic_vector(31 downto 0)  := (others => '0'); -- fpga2hps_interrupt_irq1.irq,              FPGA-to-HPS interrupts (higher 32 bits).
		fpga2hps_interrupt_irq0_irq    : in    std_logic_vector(31 downto 0)  := (others => '0'); -- fpga2hps_interrupt_irq0.irq,              FPGA-to-HPS interrupts (lower 32 bits).
		io96b0_to_hps_ch0_axil_clk     : in    std_logic                      := '0';             --           io96b0_to_hps.ch0_axil_clk,     Clock source signal. Synchronous signals are sampled on the rising edge of this clock.
		io96b0_to_hps_ch0_axil_reset_n : in    std_logic                      := '0';             --                        .ch0_axil_reset_n, Required placeholder reset. The actual bridge reset is driven by HPS Reset Manager.
		io96b0_to_hps_ch0_axil_arready : in    std_logic                      := '0';             --                        .ch0_axil_arready, Indicates a transfer on the read address channel can be accepted.
		io96b0_to_hps_ch0_axil_awready : in    std_logic                      := '0';             --                        .ch0_axil_awready, Indicates a transfer on the write address channel can be accepted.
		io96b0_to_hps_ch0_axil_bresp   : in    std_logic_vector(1 downto 0)   := (others => '0'); --                        .ch0_axil_bresp,   Indicates status of write transaction.
		io96b0_to_hps_ch0_axil_bvalid  : in    std_logic                      := '0';             --                        .ch0_axil_bvalid,  Indicates write response channel signals are valid.
		io96b0_to_hps_ch0_axil_rdata   : in    std_logic_vector(31 downto 0)  := (others => '0'); --                        .ch0_axil_rdata,   Read data.
		io96b0_to_hps_ch0_axil_rresp   : in    std_logic_vector(1 downto 0)   := (others => '0'); --                        .ch0_axil_rresp,   Indicates status of read transaction.
		io96b0_to_hps_ch0_axil_rvalid  : in    std_logic                      := '0';             --                        .ch0_axil_rvalid,  Indicates read data channel signals are valid.
		io96b0_to_hps_ch0_axil_wready  : in    std_logic                      := '0';             --                        .ch0_axil_wready,  Indicates a transfer on the write data channel can be accepted.
		io96b0_to_hps_ch0_axil_araddr  : out   std_logic_vector(26 downto 0);                     --                        .ch0_axil_araddr,  The address of the first transfer in a read transaction.
		io96b0_to_hps_ch0_axil_arvalid : out   std_logic;                                         --                        .ch0_axil_arvalid, Indicates read address channel signals are valid.
		io96b0_to_hps_ch0_axil_awaddr  : out   std_logic_vector(26 downto 0);                     --                        .ch0_axil_awaddr,  The address of the first transfer in a write transaction.
		io96b0_to_hps_ch0_axil_awvalid : out   std_logic;                                         --                        .ch0_axil_awvalid, Indicates write address channel signals are valid.
		io96b0_to_hps_ch0_axil_bready  : out   std_logic;                                         --                        .ch0_axil_bready,  Indicates a transfer on the write response channel can be accepted.
		io96b0_to_hps_ch0_axil_rready  : out   std_logic;                                         --                        .ch0_axil_rready,  Indicates a transfer on the read data channel can be accepted.
		io96b0_to_hps_ch0_axil_wdata   : out   std_logic_vector(31 downto 0);                     --                        .ch0_axil_wdata,   Write data.
		io96b0_to_hps_ch0_axil_wstrb   : out   std_logic_vector(3 downto 0);                      --                        .ch0_axil_wstrb,   Write strobes indicating which bye lanes hold valid data.
		io96b0_to_hps_ch0_axil_wvalid  : out   std_logic;                                         --                        .ch0_axil_wvalid,  Indicates write data channel signals are valid.
		io96b0_to_hps_ch0_axil_arprot  : out   std_logic_vector(2 downto 0);                      --                        .ch0_axil_arprot,  Placeholder ARPROT. Protection attributes not supported for this bridge.
		io96b0_to_hps_ch0_axil_awprot  : out   std_logic_vector(2 downto 0);                      --                        .ch0_axil_awprot,  Placegolder AWPROT. Protection attributes not supported for this bridge.
		io96b0_to_hps_axi4_ch0_clk     : in    std_logic                      := '0';             --                        .axi4_ch0_clk,     Clock source signal. Synchronous signals are sampled on the rising edge of this clock.
		io96b0_to_hps_axi4_ch0_reset_n : in    std_logic                      := '0';             --                        .axi4_ch0_reset_n, Required placeholder reset. The actual bridge reset is driven by HPS Reset Manager.
		io96b0_to_hps_axi4_ch0_arready : in    std_logic                      := '0';             --                        .axi4_ch0_arready, Indicates a transfer on the read address channel can be accepted.
		io96b0_to_hps_axi4_ch0_awready : in    std_logic                      := '0';             --                        .axi4_ch0_awready, Indicates a transfer on the write address channel can be accepted.
		io96b0_to_hps_axi4_ch0_bid     : in    std_logic_vector(6 downto 0)   := (others => '0'); --                        .axi4_ch0_bid,     Identification tag for a write response.
		io96b0_to_hps_axi4_ch0_bresp   : in    std_logic_vector(1 downto 0)   := (others => '0'); --                        .axi4_ch0_bresp,   Indicates the status of a write transaction.
		io96b0_to_hps_axi4_ch0_bvalid  : in    std_logic                      := '0';             --                        .axi4_ch0_bvalid,  Indicates write response channel signals are valid.
		io96b0_to_hps_axi4_ch0_rdata   : in    std_logic_vector(255 downto 0) := (others => '0'); --                        .axi4_ch0_rdata,   Read data.
		io96b0_to_hps_axi4_ch0_rid     : in    std_logic_vector(6 downto 0)   := (others => '0'); --                        .axi4_ch0_rid,     Identification tag for read data and response.
		io96b0_to_hps_axi4_ch0_rlast   : in    std_logic                      := '0';             --                        .axi4_ch0_rlast,   Indicates the last data transfer in a read transaction.
		io96b0_to_hps_axi4_ch0_rresp   : in    std_logic_vector(1 downto 0)   := (others => '0'); --                        .axi4_ch0_rresp,   Indicates the status of a read transfer.
		io96b0_to_hps_axi4_ch0_ruser   : in    std_logic_vector(31 downto 0)  := (others => '0'); --                        .axi4_ch0_ruser,   Extension of read data channel.
		io96b0_to_hps_axi4_ch0_rvalid  : in    std_logic                      := '0';             --                        .axi4_ch0_rvalid,  Indicates read data channel signals are valid.
		io96b0_to_hps_axi4_ch0_wready  : in    std_logic                      := '0';             --                        .axi4_ch0_wready,  Indicates a transfer on the write data channel can be accepted.
		io96b0_to_hps_axi4_ch0_araddr  : out   std_logic_vector(39 downto 0);                     --                        .axi4_ch0_araddr,  The address of the first transfer in a read transaction.
		io96b0_to_hps_axi4_ch0_arburst : out   std_logic_vector(1 downto 0);                      --                        .axi4_ch0_arburst, Burst type indicating how address changes between each transfer in a read transaction.
		io96b0_to_hps_axi4_ch0_arid    : out   std_logic_vector(6 downto 0);                      --                        .axi4_ch0_arid,    Identification tag for a read transaction.
		io96b0_to_hps_axi4_ch0_arlen   : out   std_logic_vector(7 downto 0);                      --                        .axi4_ch0_arlen,   Exact number of data transfers in a read transaction.
		io96b0_to_hps_axi4_ch0_arlock  : out   std_logic;                                         --                        .axi4_ch0_arlock,  Provides info on atomic characteristics of a read transaction.
		io96b0_to_hps_axi4_ch0_arqos   : out   std_logic_vector(3 downto 0);                      --                        .axi4_ch0_arqos,   Quality of service identifier for a read transaction.
		io96b0_to_hps_axi4_ch0_arsize  : out   std_logic_vector(2 downto 0);                      --                        .axi4_ch0_arsize,  The number of bytes in each data transfer in a read transaction.
		io96b0_to_hps_axi4_ch0_aruser  : out   std_logic_vector(13 downto 0);                     --                        .axi4_ch0_aruser,  Extension of read address channel.
		io96b0_to_hps_axi4_ch0_arvalid : out   std_logic;                                         --                        .axi4_ch0_arvalid, Indicates read address channel signals are valid.
		io96b0_to_hps_axi4_ch0_awaddr  : out   std_logic_vector(39 downto 0);                     --                        .axi4_ch0_awaddr,  The address of the first transfer in a write transaction.
		io96b0_to_hps_axi4_ch0_awburst : out   std_logic_vector(1 downto 0);                      --                        .axi4_ch0_awburst, Burst type indicating how address changes between each transfer in a write transaction.
		io96b0_to_hps_axi4_ch0_awid    : out   std_logic_vector(6 downto 0);                      --                        .axi4_ch0_awid,    Identification tag for a write transaction.
		io96b0_to_hps_axi4_ch0_awlen   : out   std_logic_vector(7 downto 0);                      --                        .axi4_ch0_awlen,   Exact number of data transfers in a write transaction.
		io96b0_to_hps_axi4_ch0_awlock  : out   std_logic;                                         --                        .axi4_ch0_awlock,  Provides info on atomic characteristics of a write transaction.
		io96b0_to_hps_axi4_ch0_awqos   : out   std_logic_vector(3 downto 0);                      --                        .axi4_ch0_awqos,   Quality of service identifier for a write transaction.
		io96b0_to_hps_axi4_ch0_awsize  : out   std_logic_vector(2 downto 0);                      --                        .axi4_ch0_awsize,  Number of bytes in each data transfer in a write transaction.
		io96b0_to_hps_axi4_ch0_awuser  : out   std_logic_vector(13 downto 0);                     --                        .axi4_ch0_awuser,  Extension of write address channel.
		io96b0_to_hps_axi4_ch0_awvalid : out   std_logic;                                         --                        .axi4_ch0_awvalid, Indicates write address channel signals are valid.
		io96b0_to_hps_axi4_ch0_bready  : out   std_logic;                                         --                        .axi4_ch0_bready,  Indicates a transfer on write response channel can be accepted.
		io96b0_to_hps_axi4_ch0_rready  : out   std_logic;                                         --                        .axi4_ch0_rready,  Indicates a transfer on read data channel can be accepted.
		io96b0_to_hps_axi4_ch0_wdata   : out   std_logic_vector(255 downto 0);                    --                        .axi4_ch0_wdata,   Write data.
		io96b0_to_hps_axi4_ch0_wlast   : out   std_logic;                                         --                        .axi4_ch0_wlast,   Indicates the last data transfer in a write transaction.
		io96b0_to_hps_axi4_ch0_wstrb   : out   std_logic_vector(31 downto 0);                     --                        .axi4_ch0_wstrb,   Write strobes indicating which byte lanes hold valid data.
		io96b0_to_hps_axi4_ch0_wuser   : out   std_logic_vector(31 downto 0);                     --                        .axi4_ch0_wuser,   Extension of the write data channel.
		io96b0_to_hps_axi4_ch0_wvalid  : out   std_logic;                                         --                        .axi4_ch0_wvalid,  Indicates write data channel signals are valid.
		io96b0_to_hps_axi4_ch0_arprot  : out   std_logic_vector(2 downto 0);                      --                        .axi4_ch0_arprot,  Placeholder ARPROT. Protection attributes not supported for this bridge.
		io96b0_to_hps_axi4_ch0_awprot  : out   std_logic_vector(2 downto 0)                       --                        .axi4_ch0_awprot,  Placeholder AWPROT. Protection attributes not supported for this bridge.
	);
end entity agilex_hps;

architecture rtl of agilex_hps is
	component agilex_hps_intel_agilex_5_soc_1400_5qvkj5y_cmp is
		port (
			h2f_reset_reset                : out   std_logic;                                         -- reset
			lwhps2fpga_axi_clock_clk       : in    std_logic                      := 'X';             -- clk
			lwhps2fpga_axi_reset_reset     : in    std_logic                      := 'X';             -- reset
			lwhps2fpga_awid                : out   std_logic_vector(3 downto 0);                      -- awid
			lwhps2fpga_awaddr              : out   std_logic_vector(28 downto 0);                     -- awaddr
			lwhps2fpga_awlen               : out   std_logic_vector(7 downto 0);                      -- awlen
			lwhps2fpga_awsize              : out   std_logic_vector(2 downto 0);                      -- awsize
			lwhps2fpga_awburst             : out   std_logic_vector(1 downto 0);                      -- awburst
			lwhps2fpga_awlock              : out   std_logic;                                         -- awlock
			lwhps2fpga_awcache             : out   std_logic_vector(3 downto 0);                      -- awcache
			lwhps2fpga_awprot              : out   std_logic_vector(2 downto 0);                      -- awprot
			lwhps2fpga_awvalid             : out   std_logic;                                         -- awvalid
			lwhps2fpga_awready             : in    std_logic                      := 'X';             -- awready
			lwhps2fpga_wdata               : out   std_logic_vector(31 downto 0);                     -- wdata
			lwhps2fpga_wstrb               : out   std_logic_vector(3 downto 0);                      -- wstrb
			lwhps2fpga_wlast               : out   std_logic;                                         -- wlast
			lwhps2fpga_wvalid              : out   std_logic;                                         -- wvalid
			lwhps2fpga_wready              : in    std_logic                      := 'X';             -- wready
			lwhps2fpga_bid                 : in    std_logic_vector(3 downto 0)   := (others => 'X'); -- bid
			lwhps2fpga_bresp               : in    std_logic_vector(1 downto 0)   := (others => 'X'); -- bresp
			lwhps2fpga_bvalid              : in    std_logic                      := 'X';             -- bvalid
			lwhps2fpga_bready              : out   std_logic;                                         -- bready
			lwhps2fpga_arid                : out   std_logic_vector(3 downto 0);                      -- arid
			lwhps2fpga_araddr              : out   std_logic_vector(28 downto 0);                     -- araddr
			lwhps2fpga_arlen               : out   std_logic_vector(7 downto 0);                      -- arlen
			lwhps2fpga_arsize              : out   std_logic_vector(2 downto 0);                      -- arsize
			lwhps2fpga_arburst             : out   std_logic_vector(1 downto 0);                      -- arburst
			lwhps2fpga_arlock              : out   std_logic;                                         -- arlock
			lwhps2fpga_arcache             : out   std_logic_vector(3 downto 0);                      -- arcache
			lwhps2fpga_arprot              : out   std_logic_vector(2 downto 0);                      -- arprot
			lwhps2fpga_arvalid             : out   std_logic;                                         -- arvalid
			lwhps2fpga_arready             : in    std_logic                      := 'X';             -- arready
			lwhps2fpga_rid                 : in    std_logic_vector(3 downto 0)   := (others => 'X'); -- rid
			lwhps2fpga_rdata               : in    std_logic_vector(31 downto 0)  := (others => 'X'); -- rdata
			lwhps2fpga_rresp               : in    std_logic_vector(1 downto 0)   := (others => 'X'); -- rresp
			lwhps2fpga_rlast               : in    std_logic                      := 'X';             -- rlast
			lwhps2fpga_rvalid              : in    std_logic                      := 'X';             -- rvalid
			lwhps2fpga_rready              : out   std_logic;                                         -- rready
			emac0_app_rst_reset_n          : out   std_logic;                                         -- reset_n
			uart0_cts_n                    : in    std_logic                      := 'X';             -- cts_n
			uart0_dcd_n                    : in    std_logic                      := 'X';             -- dcd_n
			uart0_dsr_n                    : in    std_logic                      := 'X';             -- dsr_n
			uart0_dtr_n                    : out   std_logic;                                         -- dtr_n
			uart0_out1_n                   : out   std_logic;                                         -- out1_n
			uart0_out2_n                   : out   std_logic;                                         -- out2_n
			uart0_ri_n                     : in    std_logic                      := 'X';             -- ri_n
			uart0_rts_n                    : out   std_logic;                                         -- rts_n
			uart0_rx                       : in    std_logic                      := 'X';             -- rx
			uart0_tx                       : out   std_logic;                                         -- tx
			hps_io_hps_osc_clk             : in    std_logic                      := 'X';             -- hps_osc_clk
			hps_io_sdmmc_data0             : inout std_logic                      := 'X';             -- sdmmc_data0
			hps_io_sdmmc_data1             : inout std_logic                      := 'X';             -- sdmmc_data1
			hps_io_sdmmc_cclk              : out   std_logic;                                         -- sdmmc_cclk
			hps_io_sdmmc_data2             : inout std_logic                      := 'X';             -- sdmmc_data2
			hps_io_sdmmc_data3             : inout std_logic                      := 'X';             -- sdmmc_data3
			hps_io_sdmmc_cmd               : inout std_logic                      := 'X';             -- sdmmc_cmd
			hps_io_emac0_tx_clk            : out   std_logic;                                         -- emac0_tx_clk
			hps_io_emac0_tx_ctl            : out   std_logic;                                         -- emac0_tx_ctl
			hps_io_emac0_rx_clk            : in    std_logic                      := 'X';             -- emac0_rx_clk
			hps_io_emac0_rx_ctl            : in    std_logic                      := 'X';             -- emac0_rx_ctl
			hps_io_emac0_txd0              : out   std_logic;                                         -- emac0_txd0
			hps_io_emac0_txd1              : out   std_logic;                                         -- emac0_txd1
			hps_io_emac0_rxd0              : in    std_logic                      := 'X';             -- emac0_rxd0
			hps_io_emac0_rxd1              : in    std_logic                      := 'X';             -- emac0_rxd1
			hps_io_emac0_txd2              : out   std_logic;                                         -- emac0_txd2
			hps_io_emac0_txd3              : out   std_logic;                                         -- emac0_txd3
			hps_io_emac0_rxd2              : in    std_logic                      := 'X';             -- emac0_rxd2
			hps_io_emac0_rxd3              : in    std_logic                      := 'X';             -- emac0_rxd3
			hps_io_mdio0_mdio              : inout std_logic                      := 'X';             -- mdio0_mdio
			hps_io_mdio0_mdc               : out   std_logic;                                         -- mdio0_mdc
			hps_io_uart1_tx                : out   std_logic;                                         -- uart1_tx
			hps_io_uart1_rx                : in    std_logic                      := 'X';             -- uart1_rx
			hps_io_gpio40                  : inout std_logic                      := 'X';             -- gpio40
			hps_io_gpio41                  : inout std_logic                      := 'X';             -- gpio41
			fpga2hps_interrupt_irq1_irq    : in    std_logic_vector(31 downto 0)  := (others => 'X'); -- irq
			fpga2hps_interrupt_irq0_irq    : in    std_logic_vector(31 downto 0)  := (others => 'X'); -- irq
			io96b0_to_hps_ch0_axil_clk     : in    std_logic                      := 'X';             -- ch0_axil_clk
			io96b0_to_hps_ch0_axil_reset_n : in    std_logic                      := 'X';             -- ch0_axil_reset_n
			io96b0_to_hps_ch0_axil_arready : in    std_logic                      := 'X';             -- ch0_axil_arready
			io96b0_to_hps_ch0_axil_awready : in    std_logic                      := 'X';             -- ch0_axil_awready
			io96b0_to_hps_ch0_axil_bresp   : in    std_logic_vector(1 downto 0)   := (others => 'X'); -- ch0_axil_bresp
			io96b0_to_hps_ch0_axil_bvalid  : in    std_logic                      := 'X';             -- ch0_axil_bvalid
			io96b0_to_hps_ch0_axil_rdata   : in    std_logic_vector(31 downto 0)  := (others => 'X'); -- ch0_axil_rdata
			io96b0_to_hps_ch0_axil_rresp   : in    std_logic_vector(1 downto 0)   := (others => 'X'); -- ch0_axil_rresp
			io96b0_to_hps_ch0_axil_rvalid  : in    std_logic                      := 'X';             -- ch0_axil_rvalid
			io96b0_to_hps_ch0_axil_wready  : in    std_logic                      := 'X';             -- ch0_axil_wready
			io96b0_to_hps_ch0_axil_araddr  : out   std_logic_vector(26 downto 0);                     -- ch0_axil_araddr
			io96b0_to_hps_ch0_axil_arvalid : out   std_logic;                                         -- ch0_axil_arvalid
			io96b0_to_hps_ch0_axil_awaddr  : out   std_logic_vector(26 downto 0);                     -- ch0_axil_awaddr
			io96b0_to_hps_ch0_axil_awvalid : out   std_logic;                                         -- ch0_axil_awvalid
			io96b0_to_hps_ch0_axil_bready  : out   std_logic;                                         -- ch0_axil_bready
			io96b0_to_hps_ch0_axil_rready  : out   std_logic;                                         -- ch0_axil_rready
			io96b0_to_hps_ch0_axil_wdata   : out   std_logic_vector(31 downto 0);                     -- ch0_axil_wdata
			io96b0_to_hps_ch0_axil_wstrb   : out   std_logic_vector(3 downto 0);                      -- ch0_axil_wstrb
			io96b0_to_hps_ch0_axil_wvalid  : out   std_logic;                                         -- ch0_axil_wvalid
			io96b0_to_hps_ch0_axil_arprot  : out   std_logic_vector(2 downto 0);                      -- ch0_axil_arprot
			io96b0_to_hps_ch0_axil_awprot  : out   std_logic_vector(2 downto 0);                      -- ch0_axil_awprot
			io96b0_to_hps_axi4_ch0_clk     : in    std_logic                      := 'X';             -- axi4_ch0_clk
			io96b0_to_hps_axi4_ch0_reset_n : in    std_logic                      := 'X';             -- axi4_ch0_reset_n
			io96b0_to_hps_axi4_ch0_arready : in    std_logic                      := 'X';             -- axi4_ch0_arready
			io96b0_to_hps_axi4_ch0_awready : in    std_logic                      := 'X';             -- axi4_ch0_awready
			io96b0_to_hps_axi4_ch0_bid     : in    std_logic_vector(6 downto 0)   := (others => 'X'); -- axi4_ch0_bid
			io96b0_to_hps_axi4_ch0_bresp   : in    std_logic_vector(1 downto 0)   := (others => 'X'); -- axi4_ch0_bresp
			io96b0_to_hps_axi4_ch0_bvalid  : in    std_logic                      := 'X';             -- axi4_ch0_bvalid
			io96b0_to_hps_axi4_ch0_rdata   : in    std_logic_vector(255 downto 0) := (others => 'X'); -- axi4_ch0_rdata
			io96b0_to_hps_axi4_ch0_rid     : in    std_logic_vector(6 downto 0)   := (others => 'X'); -- axi4_ch0_rid
			io96b0_to_hps_axi4_ch0_rlast   : in    std_logic                      := 'X';             -- axi4_ch0_rlast
			io96b0_to_hps_axi4_ch0_rresp   : in    std_logic_vector(1 downto 0)   := (others => 'X'); -- axi4_ch0_rresp
			io96b0_to_hps_axi4_ch0_ruser   : in    std_logic_vector(31 downto 0)  := (others => 'X'); -- axi4_ch0_ruser
			io96b0_to_hps_axi4_ch0_rvalid  : in    std_logic                      := 'X';             -- axi4_ch0_rvalid
			io96b0_to_hps_axi4_ch0_wready  : in    std_logic                      := 'X';             -- axi4_ch0_wready
			io96b0_to_hps_axi4_ch0_araddr  : out   std_logic_vector(39 downto 0);                     -- axi4_ch0_araddr
			io96b0_to_hps_axi4_ch0_arburst : out   std_logic_vector(1 downto 0);                      -- axi4_ch0_arburst
			io96b0_to_hps_axi4_ch0_arid    : out   std_logic_vector(6 downto 0);                      -- axi4_ch0_arid
			io96b0_to_hps_axi4_ch0_arlen   : out   std_logic_vector(7 downto 0);                      -- axi4_ch0_arlen
			io96b0_to_hps_axi4_ch0_arlock  : out   std_logic;                                         -- axi4_ch0_arlock
			io96b0_to_hps_axi4_ch0_arqos   : out   std_logic_vector(3 downto 0);                      -- axi4_ch0_arqos
			io96b0_to_hps_axi4_ch0_arsize  : out   std_logic_vector(2 downto 0);                      -- axi4_ch0_arsize
			io96b0_to_hps_axi4_ch0_aruser  : out   std_logic_vector(13 downto 0);                     -- axi4_ch0_aruser
			io96b0_to_hps_axi4_ch0_arvalid : out   std_logic;                                         -- axi4_ch0_arvalid
			io96b0_to_hps_axi4_ch0_awaddr  : out   std_logic_vector(39 downto 0);                     -- axi4_ch0_awaddr
			io96b0_to_hps_axi4_ch0_awburst : out   std_logic_vector(1 downto 0);                      -- axi4_ch0_awburst
			io96b0_to_hps_axi4_ch0_awid    : out   std_logic_vector(6 downto 0);                      -- axi4_ch0_awid
			io96b0_to_hps_axi4_ch0_awlen   : out   std_logic_vector(7 downto 0);                      -- axi4_ch0_awlen
			io96b0_to_hps_axi4_ch0_awlock  : out   std_logic;                                         -- axi4_ch0_awlock
			io96b0_to_hps_axi4_ch0_awqos   : out   std_logic_vector(3 downto 0);                      -- axi4_ch0_awqos
			io96b0_to_hps_axi4_ch0_awsize  : out   std_logic_vector(2 downto 0);                      -- axi4_ch0_awsize
			io96b0_to_hps_axi4_ch0_awuser  : out   std_logic_vector(13 downto 0);                     -- axi4_ch0_awuser
			io96b0_to_hps_axi4_ch0_awvalid : out   std_logic;                                         -- axi4_ch0_awvalid
			io96b0_to_hps_axi4_ch0_bready  : out   std_logic;                                         -- axi4_ch0_bready
			io96b0_to_hps_axi4_ch0_rready  : out   std_logic;                                         -- axi4_ch0_rready
			io96b0_to_hps_axi4_ch0_wdata   : out   std_logic_vector(255 downto 0);                    -- axi4_ch0_wdata
			io96b0_to_hps_axi4_ch0_wlast   : out   std_logic;                                         -- axi4_ch0_wlast
			io96b0_to_hps_axi4_ch0_wstrb   : out   std_logic_vector(31 downto 0);                     -- axi4_ch0_wstrb
			io96b0_to_hps_axi4_ch0_wuser   : out   std_logic_vector(31 downto 0);                     -- axi4_ch0_wuser
			io96b0_to_hps_axi4_ch0_wvalid  : out   std_logic;                                         -- axi4_ch0_wvalid
			io96b0_to_hps_axi4_ch0_arprot  : out   std_logic_vector(2 downto 0);                      -- axi4_ch0_arprot
			io96b0_to_hps_axi4_ch0_awprot  : out   std_logic_vector(2 downto 0)                       -- axi4_ch0_awprot
		);
	end component agilex_hps_intel_agilex_5_soc_1400_5qvkj5y_cmp;

	for agilex_hps : agilex_hps_intel_agilex_5_soc_1400_5qvkj5y_cmp
		use entity intel_agilex_5_soc_1400.agilex_hps_intel_agilex_5_soc_1400_5qvkj5y;
begin

	agilex_hps : component agilex_hps_intel_agilex_5_soc_1400_5qvkj5y_cmp
		port map (
			h2f_reset_reset                => h2f_reset_reset,                --               h2f_reset.reset
			lwhps2fpga_axi_clock_clk       => lwhps2fpga_axi_clock_clk,       --    lwhps2fpga_axi_clock.clk
			lwhps2fpga_axi_reset_reset     => lwhps2fpga_axi_reset_reset,     --    lwhps2fpga_axi_reset.reset
			lwhps2fpga_awid                => lwhps2fpga_awid,                --              lwhps2fpga.awid
			lwhps2fpga_awaddr              => lwhps2fpga_awaddr,              --                        .awaddr
			lwhps2fpga_awlen               => lwhps2fpga_awlen,               --                        .awlen
			lwhps2fpga_awsize              => lwhps2fpga_awsize,              --                        .awsize
			lwhps2fpga_awburst             => lwhps2fpga_awburst,             --                        .awburst
			lwhps2fpga_awlock              => lwhps2fpga_awlock,              --                        .awlock
			lwhps2fpga_awcache             => lwhps2fpga_awcache,             --                        .awcache
			lwhps2fpga_awprot              => lwhps2fpga_awprot,              --                        .awprot
			lwhps2fpga_awvalid             => lwhps2fpga_awvalid,             --                        .awvalid
			lwhps2fpga_awready             => lwhps2fpga_awready,             --                        .awready
			lwhps2fpga_wdata               => lwhps2fpga_wdata,               --                        .wdata
			lwhps2fpga_wstrb               => lwhps2fpga_wstrb,               --                        .wstrb
			lwhps2fpga_wlast               => lwhps2fpga_wlast,               --                        .wlast
			lwhps2fpga_wvalid              => lwhps2fpga_wvalid,              --                        .wvalid
			lwhps2fpga_wready              => lwhps2fpga_wready,              --                        .wready
			lwhps2fpga_bid                 => lwhps2fpga_bid,                 --                        .bid
			lwhps2fpga_bresp               => lwhps2fpga_bresp,               --                        .bresp
			lwhps2fpga_bvalid              => lwhps2fpga_bvalid,              --                        .bvalid
			lwhps2fpga_bready              => lwhps2fpga_bready,              --                        .bready
			lwhps2fpga_arid                => lwhps2fpga_arid,                --                        .arid
			lwhps2fpga_araddr              => lwhps2fpga_araddr,              --                        .araddr
			lwhps2fpga_arlen               => lwhps2fpga_arlen,               --                        .arlen
			lwhps2fpga_arsize              => lwhps2fpga_arsize,              --                        .arsize
			lwhps2fpga_arburst             => lwhps2fpga_arburst,             --                        .arburst
			lwhps2fpga_arlock              => lwhps2fpga_arlock,              --                        .arlock
			lwhps2fpga_arcache             => lwhps2fpga_arcache,             --                        .arcache
			lwhps2fpga_arprot              => lwhps2fpga_arprot,              --                        .arprot
			lwhps2fpga_arvalid             => lwhps2fpga_arvalid,             --                        .arvalid
			lwhps2fpga_arready             => lwhps2fpga_arready,             --                        .arready
			lwhps2fpga_rid                 => lwhps2fpga_rid,                 --                        .rid
			lwhps2fpga_rdata               => lwhps2fpga_rdata,               --                        .rdata
			lwhps2fpga_rresp               => lwhps2fpga_rresp,               --                        .rresp
			lwhps2fpga_rlast               => lwhps2fpga_rlast,               --                        .rlast
			lwhps2fpga_rvalid              => lwhps2fpga_rvalid,              --                        .rvalid
			lwhps2fpga_rready              => lwhps2fpga_rready,              --                        .rready
			emac0_app_rst_reset_n          => emac0_app_rst_reset_n,          --           emac0_app_rst.reset_n
			uart0_cts_n                    => uart0_cts_n,                    --                   uart0.cts_n
			uart0_dcd_n                    => uart0_dcd_n,                    --                        .dcd_n
			uart0_dsr_n                    => uart0_dsr_n,                    --                        .dsr_n
			uart0_dtr_n                    => uart0_dtr_n,                    --                        .dtr_n
			uart0_out1_n                   => uart0_out1_n,                   --                        .out1_n
			uart0_out2_n                   => uart0_out2_n,                   --                        .out2_n
			uart0_ri_n                     => uart0_ri_n,                     --                        .ri_n
			uart0_rts_n                    => uart0_rts_n,                    --                        .rts_n
			uart0_rx                       => uart0_rx,                       --                        .rx
			uart0_tx                       => uart0_tx,                       --                        .tx
			hps_io_hps_osc_clk             => hps_io_hps_osc_clk,             --                  hps_io.hps_osc_clk
			hps_io_sdmmc_data0             => hps_io_sdmmc_data0,             --                        .sdmmc_data0
			hps_io_sdmmc_data1             => hps_io_sdmmc_data1,             --                        .sdmmc_data1
			hps_io_sdmmc_cclk              => hps_io_sdmmc_cclk,              --                        .sdmmc_cclk
			hps_io_sdmmc_data2             => hps_io_sdmmc_data2,             --                        .sdmmc_data2
			hps_io_sdmmc_data3             => hps_io_sdmmc_data3,             --                        .sdmmc_data3
			hps_io_sdmmc_cmd               => hps_io_sdmmc_cmd,               --                        .sdmmc_cmd
			hps_io_emac0_tx_clk            => hps_io_emac0_tx_clk,            --                        .emac0_tx_clk
			hps_io_emac0_tx_ctl            => hps_io_emac0_tx_ctl,            --                        .emac0_tx_ctl
			hps_io_emac0_rx_clk            => hps_io_emac0_rx_clk,            --                        .emac0_rx_clk
			hps_io_emac0_rx_ctl            => hps_io_emac0_rx_ctl,            --                        .emac0_rx_ctl
			hps_io_emac0_txd0              => hps_io_emac0_txd0,              --                        .emac0_txd0
			hps_io_emac0_txd1              => hps_io_emac0_txd1,              --                        .emac0_txd1
			hps_io_emac0_rxd0              => hps_io_emac0_rxd0,              --                        .emac0_rxd0
			hps_io_emac0_rxd1              => hps_io_emac0_rxd1,              --                        .emac0_rxd1
			hps_io_emac0_txd2              => hps_io_emac0_txd2,              --                        .emac0_txd2
			hps_io_emac0_txd3              => hps_io_emac0_txd3,              --                        .emac0_txd3
			hps_io_emac0_rxd2              => hps_io_emac0_rxd2,              --                        .emac0_rxd2
			hps_io_emac0_rxd3              => hps_io_emac0_rxd3,              --                        .emac0_rxd3
			hps_io_mdio0_mdio              => hps_io_mdio0_mdio,              --                        .mdio0_mdio
			hps_io_mdio0_mdc               => hps_io_mdio0_mdc,               --                        .mdio0_mdc
			hps_io_uart1_tx                => hps_io_uart1_tx,                --                        .uart1_tx
			hps_io_uart1_rx                => hps_io_uart1_rx,                --                        .uart1_rx
			hps_io_gpio40                  => hps_io_gpio40,                  --                        .gpio40
			hps_io_gpio41                  => hps_io_gpio41,                  --                        .gpio41
			fpga2hps_interrupt_irq1_irq    => fpga2hps_interrupt_irq1_irq,    -- fpga2hps_interrupt_irq1.irq
			fpga2hps_interrupt_irq0_irq    => fpga2hps_interrupt_irq0_irq,    -- fpga2hps_interrupt_irq0.irq
			io96b0_to_hps_ch0_axil_clk     => io96b0_to_hps_ch0_axil_clk,     --           io96b0_to_hps.ch0_axil_clk
			io96b0_to_hps_ch0_axil_reset_n => io96b0_to_hps_ch0_axil_reset_n, --                        .ch0_axil_reset_n
			io96b0_to_hps_ch0_axil_arready => io96b0_to_hps_ch0_axil_arready, --                        .ch0_axil_arready
			io96b0_to_hps_ch0_axil_awready => io96b0_to_hps_ch0_axil_awready, --                        .ch0_axil_awready
			io96b0_to_hps_ch0_axil_bresp   => io96b0_to_hps_ch0_axil_bresp,   --                        .ch0_axil_bresp
			io96b0_to_hps_ch0_axil_bvalid  => io96b0_to_hps_ch0_axil_bvalid,  --                        .ch0_axil_bvalid
			io96b0_to_hps_ch0_axil_rdata   => io96b0_to_hps_ch0_axil_rdata,   --                        .ch0_axil_rdata
			io96b0_to_hps_ch0_axil_rresp   => io96b0_to_hps_ch0_axil_rresp,   --                        .ch0_axil_rresp
			io96b0_to_hps_ch0_axil_rvalid  => io96b0_to_hps_ch0_axil_rvalid,  --                        .ch0_axil_rvalid
			io96b0_to_hps_ch0_axil_wready  => io96b0_to_hps_ch0_axil_wready,  --                        .ch0_axil_wready
			io96b0_to_hps_ch0_axil_araddr  => io96b0_to_hps_ch0_axil_araddr,  --                        .ch0_axil_araddr
			io96b0_to_hps_ch0_axil_arvalid => io96b0_to_hps_ch0_axil_arvalid, --                        .ch0_axil_arvalid
			io96b0_to_hps_ch0_axil_awaddr  => io96b0_to_hps_ch0_axil_awaddr,  --                        .ch0_axil_awaddr
			io96b0_to_hps_ch0_axil_awvalid => io96b0_to_hps_ch0_axil_awvalid, --                        .ch0_axil_awvalid
			io96b0_to_hps_ch0_axil_bready  => io96b0_to_hps_ch0_axil_bready,  --                        .ch0_axil_bready
			io96b0_to_hps_ch0_axil_rready  => io96b0_to_hps_ch0_axil_rready,  --                        .ch0_axil_rready
			io96b0_to_hps_ch0_axil_wdata   => io96b0_to_hps_ch0_axil_wdata,   --                        .ch0_axil_wdata
			io96b0_to_hps_ch0_axil_wstrb   => io96b0_to_hps_ch0_axil_wstrb,   --                        .ch0_axil_wstrb
			io96b0_to_hps_ch0_axil_wvalid  => io96b0_to_hps_ch0_axil_wvalid,  --                        .ch0_axil_wvalid
			io96b0_to_hps_ch0_axil_arprot  => io96b0_to_hps_ch0_axil_arprot,  --                        .ch0_axil_arprot
			io96b0_to_hps_ch0_axil_awprot  => io96b0_to_hps_ch0_axil_awprot,  --                        .ch0_axil_awprot
			io96b0_to_hps_axi4_ch0_clk     => io96b0_to_hps_axi4_ch0_clk,     --                        .axi4_ch0_clk
			io96b0_to_hps_axi4_ch0_reset_n => io96b0_to_hps_axi4_ch0_reset_n, --                        .axi4_ch0_reset_n
			io96b0_to_hps_axi4_ch0_arready => io96b0_to_hps_axi4_ch0_arready, --                        .axi4_ch0_arready
			io96b0_to_hps_axi4_ch0_awready => io96b0_to_hps_axi4_ch0_awready, --                        .axi4_ch0_awready
			io96b0_to_hps_axi4_ch0_bid     => io96b0_to_hps_axi4_ch0_bid,     --                        .axi4_ch0_bid
			io96b0_to_hps_axi4_ch0_bresp   => io96b0_to_hps_axi4_ch0_bresp,   --                        .axi4_ch0_bresp
			io96b0_to_hps_axi4_ch0_bvalid  => io96b0_to_hps_axi4_ch0_bvalid,  --                        .axi4_ch0_bvalid
			io96b0_to_hps_axi4_ch0_rdata   => io96b0_to_hps_axi4_ch0_rdata,   --                        .axi4_ch0_rdata
			io96b0_to_hps_axi4_ch0_rid     => io96b0_to_hps_axi4_ch0_rid,     --                        .axi4_ch0_rid
			io96b0_to_hps_axi4_ch0_rlast   => io96b0_to_hps_axi4_ch0_rlast,   --                        .axi4_ch0_rlast
			io96b0_to_hps_axi4_ch0_rresp   => io96b0_to_hps_axi4_ch0_rresp,   --                        .axi4_ch0_rresp
			io96b0_to_hps_axi4_ch0_ruser   => io96b0_to_hps_axi4_ch0_ruser,   --                        .axi4_ch0_ruser
			io96b0_to_hps_axi4_ch0_rvalid  => io96b0_to_hps_axi4_ch0_rvalid,  --                        .axi4_ch0_rvalid
			io96b0_to_hps_axi4_ch0_wready  => io96b0_to_hps_axi4_ch0_wready,  --                        .axi4_ch0_wready
			io96b0_to_hps_axi4_ch0_araddr  => io96b0_to_hps_axi4_ch0_araddr,  --                        .axi4_ch0_araddr
			io96b0_to_hps_axi4_ch0_arburst => io96b0_to_hps_axi4_ch0_arburst, --                        .axi4_ch0_arburst
			io96b0_to_hps_axi4_ch0_arid    => io96b0_to_hps_axi4_ch0_arid,    --                        .axi4_ch0_arid
			io96b0_to_hps_axi4_ch0_arlen   => io96b0_to_hps_axi4_ch0_arlen,   --                        .axi4_ch0_arlen
			io96b0_to_hps_axi4_ch0_arlock  => io96b0_to_hps_axi4_ch0_arlock,  --                        .axi4_ch0_arlock
			io96b0_to_hps_axi4_ch0_arqos   => io96b0_to_hps_axi4_ch0_arqos,   --                        .axi4_ch0_arqos
			io96b0_to_hps_axi4_ch0_arsize  => io96b0_to_hps_axi4_ch0_arsize,  --                        .axi4_ch0_arsize
			io96b0_to_hps_axi4_ch0_aruser  => io96b0_to_hps_axi4_ch0_aruser,  --                        .axi4_ch0_aruser
			io96b0_to_hps_axi4_ch0_arvalid => io96b0_to_hps_axi4_ch0_arvalid, --                        .axi4_ch0_arvalid
			io96b0_to_hps_axi4_ch0_awaddr  => io96b0_to_hps_axi4_ch0_awaddr,  --                        .axi4_ch0_awaddr
			io96b0_to_hps_axi4_ch0_awburst => io96b0_to_hps_axi4_ch0_awburst, --                        .axi4_ch0_awburst
			io96b0_to_hps_axi4_ch0_awid    => io96b0_to_hps_axi4_ch0_awid,    --                        .axi4_ch0_awid
			io96b0_to_hps_axi4_ch0_awlen   => io96b0_to_hps_axi4_ch0_awlen,   --                        .axi4_ch0_awlen
			io96b0_to_hps_axi4_ch0_awlock  => io96b0_to_hps_axi4_ch0_awlock,  --                        .axi4_ch0_awlock
			io96b0_to_hps_axi4_ch0_awqos   => io96b0_to_hps_axi4_ch0_awqos,   --                        .axi4_ch0_awqos
			io96b0_to_hps_axi4_ch0_awsize  => io96b0_to_hps_axi4_ch0_awsize,  --                        .axi4_ch0_awsize
			io96b0_to_hps_axi4_ch0_awuser  => io96b0_to_hps_axi4_ch0_awuser,  --                        .axi4_ch0_awuser
			io96b0_to_hps_axi4_ch0_awvalid => io96b0_to_hps_axi4_ch0_awvalid, --                        .axi4_ch0_awvalid
			io96b0_to_hps_axi4_ch0_bready  => io96b0_to_hps_axi4_ch0_bready,  --                        .axi4_ch0_bready
			io96b0_to_hps_axi4_ch0_rready  => io96b0_to_hps_axi4_ch0_rready,  --                        .axi4_ch0_rready
			io96b0_to_hps_axi4_ch0_wdata   => io96b0_to_hps_axi4_ch0_wdata,   --                        .axi4_ch0_wdata
			io96b0_to_hps_axi4_ch0_wlast   => io96b0_to_hps_axi4_ch0_wlast,   --                        .axi4_ch0_wlast
			io96b0_to_hps_axi4_ch0_wstrb   => io96b0_to_hps_axi4_ch0_wstrb,   --                        .axi4_ch0_wstrb
			io96b0_to_hps_axi4_ch0_wuser   => io96b0_to_hps_axi4_ch0_wuser,   --                        .axi4_ch0_wuser
			io96b0_to_hps_axi4_ch0_wvalid  => io96b0_to_hps_axi4_ch0_wvalid,  --                        .axi4_ch0_wvalid
			io96b0_to_hps_axi4_ch0_arprot  => io96b0_to_hps_axi4_ch0_arprot,  --                        .axi4_ch0_arprot
			io96b0_to_hps_axi4_ch0_awprot  => io96b0_to_hps_axi4_ch0_awprot   --                        .axi4_ch0_awprot
		);

end architecture rtl; -- of agilex_hps
