-- emif_io96b_hps_emif_io96b_hps_420_dyxenzq_refclk_gpio.vhd

-- Generated using ACDS version 26.1 110

library IEEE;
library altera_gpio_2300;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity emif_io96b_hps_emif_io96b_hps_420_dyxenzq_refclk_gpio is
	port (
		dout   : out std_logic_vector(0 downto 0);                    --   dout.export, Data output to the FPGA core in input or bidirectional mode, DATA_SIZE depends on the register mode: Bypass or simple register - DATA_SIZE = SIZE DDIO - DATA_SIZE = 2 x SIZE
		pad_in : in  std_logic_vector(0 downto 0) := (others => '0')  -- pad_in.export, Input signal from the pad.
	);
end entity emif_io96b_hps_emif_io96b_hps_420_dyxenzq_refclk_gpio;

architecture rtl of emif_io96b_hps_emif_io96b_hps_420_dyxenzq_refclk_gpio is
	component emif_io96b_hps_emif_io96b_hps_420_dyxenzq_refclk_gpio_altera_gpio_2300_ctzjwfq_cmp is
		port (
			dout   : out std_logic_vector(0 downto 0);                    -- export
			pad_in : in  std_logic_vector(0 downto 0) := (others => 'X')  -- export
		);
	end component emif_io96b_hps_emif_io96b_hps_420_dyxenzq_refclk_gpio_altera_gpio_2300_ctzjwfq_cmp;

	for refclk_gpio : emif_io96b_hps_emif_io96b_hps_420_dyxenzq_refclk_gpio_altera_gpio_2300_ctzjwfq_cmp
		use entity altera_gpio_2300.emif_io96b_hps_emif_io96b_hps_420_dyxenzq_refclk_gpio_altera_gpio_2300_ctzjwfq;
begin

	refclk_gpio : component emif_io96b_hps_emif_io96b_hps_420_dyxenzq_refclk_gpio_altera_gpio_2300_ctzjwfq_cmp
		port map (
			dout   => dout,   --   dout.export
			pad_in => pad_in  -- pad_in.export
		);

end architecture rtl; -- of emif_io96b_hps_emif_io96b_hps_420_dyxenzq_refclk_gpio
