-- hps_subsys_s10_user_rst_clkgate_0.vhd

-- Generated using ACDS version 26.1.1 130

library IEEE;
library altera_s10_user_rst_clkgate_1949;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hps_subsys_s10_user_rst_clkgate_0 is
	port (
		ninit_done : out std_logic   -- ninit_done.reset, You can use the nINIT_DONE signal in one of the following ways: To gate an external or internal reset; To gate the reset input to the transceiver and I/O PLLs; To gate the write enable of design blocks such as embedded memory blocks, state machine, and shift registers; To synchronously drive register reset input ports in your design.
	);
end entity hps_subsys_s10_user_rst_clkgate_0;

architecture rtl of hps_subsys_s10_user_rst_clkgate_0 is
	component altera_s10_user_rst_clkgate_cmp is
		port (
			ninit_done : out std_logic   -- reset
		);
	end component altera_s10_user_rst_clkgate_cmp;

	for s10_user_rst_clkgate_0 : altera_s10_user_rst_clkgate_cmp
		use entity altera_s10_user_rst_clkgate_1949.altera_s10_user_rst_clkgate;
begin

	s10_user_rst_clkgate_0 : component altera_s10_user_rst_clkgate_cmp
		port map (
			ninit_done => ninit_done  -- ninit_done.reset
		);

end architecture rtl; -- of hps_subsys_s10_user_rst_clkgate_0
