-- emif_io96b_hps_emif_io96b_hps_500_j4t3edi_refclk_bridge.vhd

-- Generated using ACDS version 26.1.1 130

library IEEE;
library qsys_interface_bridge_10;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity emif_io96b_hps_emif_io96b_hps_500_j4t3edi_refclk_bridge is
	port (
		refclk_in       : in  std_logic := '0'; --       refclk_in.clk
		refclk_out      : out std_logic;        --      refclk_out.clk
		refclk_in_gpio  : out std_logic;        --  refclk_in_gpio.export
		refclk_out_gpio : in  std_logic := '0'  -- refclk_out_gpio.export
	);
end entity emif_io96b_hps_emif_io96b_hps_500_j4t3edi_refclk_bridge;

architecture rtl of emif_io96b_hps_emif_io96b_hps_500_j4t3edi_refclk_bridge is
	component emif_io96b_hps_emif_io96b_hps_500_j4t3edi_refclk_bridge_qsys_interface_bridge_10_tos2vpi_cmp is
		port (
			refclk_in       : in  std_logic := 'X'; -- clk
			refclk_out      : out std_logic;        -- clk
			refclk_in_gpio  : out std_logic;        -- export
			refclk_out_gpio : in  std_logic := 'X'  -- export
		);
	end component emif_io96b_hps_emif_io96b_hps_500_j4t3edi_refclk_bridge_qsys_interface_bridge_10_tos2vpi_cmp;

	for refclk_bridge : emif_io96b_hps_emif_io96b_hps_500_j4t3edi_refclk_bridge_qsys_interface_bridge_10_tos2vpi_cmp
		use entity qsys_interface_bridge_10.emif_io96b_hps_emif_io96b_hps_500_j4t3edi_refclk_bridge_qsys_interface_bridge_10_tos2vpi;
begin

	refclk_bridge : component emif_io96b_hps_emif_io96b_hps_500_j4t3edi_refclk_bridge_qsys_interface_bridge_10_tos2vpi_cmp
		port map (
			refclk_in       => refclk_in,       --       refclk_in.clk
			refclk_out      => refclk_out,      --      refclk_out.clk
			refclk_in_gpio  => refclk_in_gpio,  --  refclk_in_gpio.export
			refclk_out_gpio => refclk_out_gpio  -- refclk_out_gpio.export
		);

end architecture rtl; -- of emif_io96b_hps_emif_io96b_hps_500_j4t3edi_refclk_bridge
