-- emif_io96b_hps_emif_io96b_hps_420_dyxenzq_emif_0_lpddr4_emif_io96b_lpddr4_emif_io96b_cal_420_65qugki.vhd

-- Generated using ACDS version 26.1 110

library IEEE;
library emif_io96b_cal_232;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity emif_io96b_hps_emif_io96b_hps_420_dyxenzq_emif_0_lpddr4_emif_io96b_lpddr4_emif_io96b_cal_420_65qugki is
	generic (
		NUM_CALBUS_PERIPHS : integer := 1;
		NUM_CALBUS_PLLS    : integer := 0;
		PORT_S_AXIL_MODE   : string  := "HARD_PATH";
		DEBUG_TOOLS_EN     : boolean := false;
		PORT_M_AXIL_ENABLE : boolean := false
	);
	port (
		periph_calbus_0             : out std_logic_vector(1341 downto 0);                     --       calbus_periph_0.calbus,             Interface to periphery 0 - command
		periph_calbus_readdata_0    : in  std_logic_vector(1314 downto 0)  := (others => '0'); --                      .calbus_readdata,    Interface to periphery 0 - read data
		periph_calbus_param_table_0 : in  std_logic_vector(32767 downto 0) := (others => '0'); --                      .calbus_param_table, Interface to periphery 0 - param table
		periph_calbus_1             : out std_logic_vector(1341 downto 0);                     --       calbus_periph_1.calbus,             Interface to periphery 1 - command
		periph_calbus_readdata_1    : in  std_logic_vector(1314 downto 0)  := (others => '0'); --                      .calbus_readdata,    Interface to periphery 1 - read data
		periph_calbus_param_table_1 : in  std_logic_vector(32767 downto 0) := (others => '0'); --                      .calbus_param_table, Interface to periphery 1 - param table
		pll_calbus_0                : out std_logic_vector(57 downto 0);                       --          calbus_pll_0.calbus,             Interface to PLL 0 - command
		pll_calbus_readdata_0       : in  std_logic_vector(31 downto 0)    := (others => '0'); --                      .calbus_readdata,    Interface to PLL 0 - read data
		pll_calbus_1                : out std_logic_vector(57 downto 0);                       --          calbus_pll_1.calbus,             Interface to PLL 1 - command
		pll_calbus_readdata_1       : in  std_logic_vector(31 downto 0)    := (others => '0'); --                      .calbus_readdata,    Interface to PLL 1 - read data
		pll_calbus_2                : out std_logic_vector(57 downto 0);                       --          calbus_pll_2.calbus,             Interface to PLL 2 - command
		pll_calbus_readdata_2       : in  std_logic_vector(31 downto 0)    := (others => '0'); --                      .calbus_readdata,    Interface to PLL 2 - read data
		s0_axi4lite_clk             : in  std_logic                        := '0';             --       s0_axi4lite_clk.clk,                Axi-lite clock
		s0_axi4lite_rst_n           : in  std_logic                        := '0';             --     s0_axi4lite_rst_n.reset_n,            Axi-lite reset_n
		s0_axi4lite_awaddr          : in  std_logic_vector(26 downto 0)    := (others => '0'); --           s0_axi4lite.awaddr,             Axi-lite awaddr
		s0_axi4lite_awvalid         : in  std_logic                        := '0';             --                      .awvalid,            Axi-lite awvalid
		s0_axi4lite_awready         : out std_logic;                                           --                      .awready,            Axi-lite awready
		s0_axi4lite_araddr          : in  std_logic_vector(26 downto 0)    := (others => '0'); --                      .araddr,             Axi-lite araddr
		s0_axi4lite_arvalid         : in  std_logic                        := '0';             --                      .arvalid,            Axi-lite arvalid
		s0_axi4lite_arready         : out std_logic;                                           --                      .arready,            Axi-lite arready
		s0_axi4lite_wdata           : in  std_logic_vector(31 downto 0)    := (others => '0'); --                      .wdata,              Axi-lite wdata
		s0_axi4lite_wvalid          : in  std_logic                        := '0';             --                      .wvalid,             Axi-lite wvalid
		s0_axi4lite_wready          : out std_logic;                                           --                      .wready,             Axi-lite wready
		s0_axi4lite_rresp           : out std_logic_vector(1 downto 0);                        --                      .rresp,              Axi-lite rresp
		s0_axi4lite_rdata           : out std_logic_vector(31 downto 0);                       --                      .rdata,              Axi-lite rdata
		s0_axi4lite_rvalid          : out std_logic;                                           --                      .rvalid,             Axi-lite rvalid
		s0_axi4lite_rready          : in  std_logic                        := '0';             --                      .rready,             Axi-lite rready
		s0_axi4lite_bresp           : out std_logic_vector(1 downto 0);                        --                      .bresp,              Axi-lite bresp
		s0_axi4lite_bvalid          : out std_logic;                                           --                      .bvalid,             Axi-lite bvalid
		s0_axi4lite_bready          : in  std_logic                        := '0';             --                      .bready,             Axi-lite bready
		s0_axi4lite_awprot          : in  std_logic_vector(2 downto 0)     := (others => '0'); --                      .awprot,             Axi-lite awprot
		s0_axi4lite_arprot          : in  std_logic_vector(2 downto 0)     := (others => '0'); --                      .arprot,             Axi-lite arprot
		s0_axi4lite_wstrb           : in  std_logic_vector(3 downto 0)     := (others => '0'); --                      .wstrb,              Axi-lite wstrb
		m0_axi4lite_awaddr          : out std_logic_vector(26 downto 0);                       --           m0_axi4lite.awaddr
		m0_axi4lite_awvalid         : out std_logic;                                           --                      .awvalid
		m0_axi4lite_awready         : in  std_logic                        := '0';             --                      .awready
		m0_axi4lite_araddr          : out std_logic_vector(26 downto 0);                       --                      .araddr
		m0_axi4lite_arvalid         : out std_logic;                                           --                      .arvalid
		m0_axi4lite_arready         : in  std_logic                        := '0';             --                      .arready
		m0_axi4lite_wdata           : out std_logic_vector(31 downto 0);                       --                      .wdata
		m0_axi4lite_wvalid          : out std_logic;                                           --                      .wvalid
		m0_axi4lite_wready          : in  std_logic                        := '0';             --                      .wready
		m0_axi4lite_rresp           : in  std_logic_vector(1 downto 0)     := (others => '0'); --                      .rresp
		m0_axi4lite_rdata           : in  std_logic_vector(31 downto 0)    := (others => '0'); --                      .rdata
		m0_axi4lite_rvalid          : in  std_logic                        := '0';             --                      .rvalid
		m0_axi4lite_rready          : out std_logic;                                           --                      .rready
		m0_axi4lite_bresp           : in  std_logic_vector(1 downto 0)     := (others => '0'); --                      .bresp
		m0_axi4lite_bvalid          : in  std_logic                        := '0';             --                      .bvalid
		m0_axi4lite_bready          : out std_logic;                                           --                      .bready
		m0_axi4lite_awprot          : out std_logic_vector(2 downto 0);                        --                      .awprot
		m0_axi4lite_arprot          : out std_logic_vector(2 downto 0);                        --                      .arprot
		m0_axi4lite_wstrb           : out std_logic_vector(3 downto 0);                        --                      .wstrb
		s0_noc_axi4lite_clk         : out std_logic;                                           --   s0_noc_axi4lite_clk.clk
		s0_noc_axi4lite_rst_n       : out std_logic;                                           -- s0_noc_axi4lite_rst_n.reset_n
		s0_noc_axi4lite_awaddr      : in  std_logic_vector(26 downto 0)    := (others => '0'); --       s0_noc_axi4lite.awaddr
		s0_noc_axi4lite_awvalid     : in  std_logic                        := '0';             --                      .awvalid
		s0_noc_axi4lite_awready     : out std_logic;                                           --                      .awready
		s0_noc_axi4lite_araddr      : in  std_logic_vector(26 downto 0)    := (others => '0'); --                      .araddr
		s0_noc_axi4lite_arvalid     : in  std_logic                        := '0';             --                      .arvalid
		s0_noc_axi4lite_arready     : out std_logic;                                           --                      .arready
		s0_noc_axi4lite_wdata       : in  std_logic_vector(31 downto 0)    := (others => '0'); --                      .wdata
		s0_noc_axi4lite_wvalid      : in  std_logic                        := '0';             --                      .wvalid
		s0_noc_axi4lite_wready      : out std_logic;                                           --                      .wready
		s0_noc_axi4lite_rresp       : out std_logic_vector(1 downto 0);                        --                      .rresp
		s0_noc_axi4lite_rdata       : out std_logic_vector(31 downto 0);                       --                      .rdata
		s0_noc_axi4lite_rvalid      : out std_logic;                                           --                      .rvalid
		s0_noc_axi4lite_rready      : in  std_logic                        := '0';             --                      .rready
		s0_noc_axi4lite_bresp       : out std_logic_vector(1 downto 0);                        --                      .bresp
		s0_noc_axi4lite_bvalid      : out std_logic;                                           --                      .bvalid
		s0_noc_axi4lite_bready      : in  std_logic                        := '0';             --                      .bready
		s0_noc_axi4lite_awprot      : in  std_logic_vector(2 downto 0)     := (others => '0'); --                      .awprot
		s0_noc_axi4lite_arprot      : in  std_logic_vector(2 downto 0)     := (others => '0'); --                      .arprot
		s0_noc_axi4lite_wstrb       : in  std_logic_vector(3 downto 0)     := (others => '0'); --                      .wstrb
		tniul_rst_n                 : in  std_logic                        := '0';             --   s0_tniulite_reset_n.reset_n
		ls_to_cal                   : in  std_logic_vector(7 downto 0)     := (others => '0'); --                    ls.ls_to_cal
		ls_from_cal                 : out std_logic_vector(7 downto 0);                        --                      .ls_from_cal
		fbr_c2f_rst_n               : in  std_logic                        := '0'              --                      .fbr_c2f_rst_n
	);
end entity emif_io96b_hps_emif_io96b_hps_420_dyxenzq_emif_0_lpddr4_emif_io96b_lpddr4_emif_io96b_cal_420_65qugki;

architecture rtl of emif_io96b_hps_emif_io96b_hps_420_dyxenzq_emif_0_lpddr4_emif_io96b_lpddr4_emif_io96b_cal_420_65qugki is
	component emif_io96b_hps_emif_io96b_hps_420_dyxenzq_emif_0_lpddr4_emif_io96b_cal_232_s5h5wki_cmp is
		generic (
			NUM_CALBUS_PERIPHS : integer := 1;
			NUM_CALBUS_PLLS    : integer := 0;
			PORT_S_AXIL_MODE   : string  := "DISABLE";
			DEBUG_TOOLS_EN     : boolean := false;
			PORT_M_AXIL_ENABLE : boolean := false
		);
		port (
			periph_calbus_0             : out std_logic_vector(1341 downto 0);                     -- calbus
			periph_calbus_readdata_0    : in  std_logic_vector(1314 downto 0)  := (others => 'X'); -- calbus_readdata
			periph_calbus_param_table_0 : in  std_logic_vector(32767 downto 0) := (others => 'X'); -- calbus_param_table
			periph_calbus_1             : out std_logic_vector(1341 downto 0);                     -- calbus
			periph_calbus_readdata_1    : in  std_logic_vector(1314 downto 0)  := (others => 'X'); -- calbus_readdata
			periph_calbus_param_table_1 : in  std_logic_vector(32767 downto 0) := (others => 'X'); -- calbus_param_table
			pll_calbus_0                : out std_logic_vector(57 downto 0);                       -- calbus
			pll_calbus_readdata_0       : in  std_logic_vector(31 downto 0)    := (others => 'X'); -- calbus_readdata
			pll_calbus_1                : out std_logic_vector(57 downto 0);                       -- calbus
			pll_calbus_readdata_1       : in  std_logic_vector(31 downto 0)    := (others => 'X'); -- calbus_readdata
			pll_calbus_2                : out std_logic_vector(57 downto 0);                       -- calbus
			pll_calbus_readdata_2       : in  std_logic_vector(31 downto 0)    := (others => 'X'); -- calbus_readdata
			s0_axi4lite_clk             : in  std_logic                        := 'X';             -- clk
			s0_axi4lite_rst_n           : in  std_logic                        := 'X';             -- reset_n
			s0_axi4lite_awaddr          : in  std_logic_vector(26 downto 0)    := (others => 'X'); -- awaddr
			s0_axi4lite_awvalid         : in  std_logic                        := 'X';             -- awvalid
			s0_axi4lite_awready         : out std_logic;                                           -- awready
			s0_axi4lite_araddr          : in  std_logic_vector(26 downto 0)    := (others => 'X'); -- araddr
			s0_axi4lite_arvalid         : in  std_logic                        := 'X';             -- arvalid
			s0_axi4lite_arready         : out std_logic;                                           -- arready
			s0_axi4lite_wdata           : in  std_logic_vector(31 downto 0)    := (others => 'X'); -- wdata
			s0_axi4lite_wvalid          : in  std_logic                        := 'X';             -- wvalid
			s0_axi4lite_wready          : out std_logic;                                           -- wready
			s0_axi4lite_rresp           : out std_logic_vector(1 downto 0);                        -- rresp
			s0_axi4lite_rdata           : out std_logic_vector(31 downto 0);                       -- rdata
			s0_axi4lite_rvalid          : out std_logic;                                           -- rvalid
			s0_axi4lite_rready          : in  std_logic                        := 'X';             -- rready
			s0_axi4lite_bresp           : out std_logic_vector(1 downto 0);                        -- bresp
			s0_axi4lite_bvalid          : out std_logic;                                           -- bvalid
			s0_axi4lite_bready          : in  std_logic                        := 'X';             -- bready
			s0_axi4lite_awprot          : in  std_logic_vector(2 downto 0)     := (others => 'X'); -- awprot
			s0_axi4lite_arprot          : in  std_logic_vector(2 downto 0)     := (others => 'X'); -- arprot
			s0_axi4lite_wstrb           : in  std_logic_vector(3 downto 0)     := (others => 'X'); -- wstrb
			m0_axi4lite_awaddr          : out std_logic_vector(26 downto 0);                       -- awaddr
			m0_axi4lite_awvalid         : out std_logic;                                           -- awvalid
			m0_axi4lite_awready         : in  std_logic                        := 'X';             -- awready
			m0_axi4lite_araddr          : out std_logic_vector(26 downto 0);                       -- araddr
			m0_axi4lite_arvalid         : out std_logic;                                           -- arvalid
			m0_axi4lite_arready         : in  std_logic                        := 'X';             -- arready
			m0_axi4lite_wdata           : out std_logic_vector(31 downto 0);                       -- wdata
			m0_axi4lite_wvalid          : out std_logic;                                           -- wvalid
			m0_axi4lite_wready          : in  std_logic                        := 'X';             -- wready
			m0_axi4lite_rresp           : in  std_logic_vector(1 downto 0)     := (others => 'X'); -- rresp
			m0_axi4lite_rdata           : in  std_logic_vector(31 downto 0)    := (others => 'X'); -- rdata
			m0_axi4lite_rvalid          : in  std_logic                        := 'X';             -- rvalid
			m0_axi4lite_rready          : out std_logic;                                           -- rready
			m0_axi4lite_bresp           : in  std_logic_vector(1 downto 0)     := (others => 'X'); -- bresp
			m0_axi4lite_bvalid          : in  std_logic                        := 'X';             -- bvalid
			m0_axi4lite_bready          : out std_logic;                                           -- bready
			m0_axi4lite_awprot          : out std_logic_vector(2 downto 0);                        -- awprot
			m0_axi4lite_arprot          : out std_logic_vector(2 downto 0);                        -- arprot
			m0_axi4lite_wstrb           : out std_logic_vector(3 downto 0);                        -- wstrb
			s0_noc_axi4lite_clk         : out std_logic;                                           -- clk
			s0_noc_axi4lite_rst_n       : out std_logic;                                           -- reset_n
			s0_noc_axi4lite_awaddr      : in  std_logic_vector(26 downto 0)    := (others => 'X'); -- awaddr
			s0_noc_axi4lite_awvalid     : in  std_logic                        := 'X';             -- awvalid
			s0_noc_axi4lite_awready     : out std_logic;                                           -- awready
			s0_noc_axi4lite_araddr      : in  std_logic_vector(26 downto 0)    := (others => 'X'); -- araddr
			s0_noc_axi4lite_arvalid     : in  std_logic                        := 'X';             -- arvalid
			s0_noc_axi4lite_arready     : out std_logic;                                           -- arready
			s0_noc_axi4lite_wdata       : in  std_logic_vector(31 downto 0)    := (others => 'X'); -- wdata
			s0_noc_axi4lite_wvalid      : in  std_logic                        := 'X';             -- wvalid
			s0_noc_axi4lite_wready      : out std_logic;                                           -- wready
			s0_noc_axi4lite_rresp       : out std_logic_vector(1 downto 0);                        -- rresp
			s0_noc_axi4lite_rdata       : out std_logic_vector(31 downto 0);                       -- rdata
			s0_noc_axi4lite_rvalid      : out std_logic;                                           -- rvalid
			s0_noc_axi4lite_rready      : in  std_logic                        := 'X';             -- rready
			s0_noc_axi4lite_bresp       : out std_logic_vector(1 downto 0);                        -- bresp
			s0_noc_axi4lite_bvalid      : out std_logic;                                           -- bvalid
			s0_noc_axi4lite_bready      : in  std_logic                        := 'X';             -- bready
			s0_noc_axi4lite_awprot      : in  std_logic_vector(2 downto 0)     := (others => 'X'); -- awprot
			s0_noc_axi4lite_arprot      : in  std_logic_vector(2 downto 0)     := (others => 'X'); -- arprot
			s0_noc_axi4lite_wstrb       : in  std_logic_vector(3 downto 0)     := (others => 'X'); -- wstrb
			tniul_rst_n                 : in  std_logic                        := 'X';             -- reset_n
			ls_to_cal                   : in  std_logic_vector(7 downto 0)     := (others => 'X'); -- ls_to_cal
			ls_from_cal                 : out std_logic_vector(7 downto 0);                        -- ls_from_cal
			fbr_c2f_rst_n               : in  std_logic                        := 'X'              -- fbr_c2f_rst_n
		);
	end component emif_io96b_hps_emif_io96b_hps_420_dyxenzq_emif_0_lpddr4_emif_io96b_cal_232_s5h5wki_cmp;

	for cal_0 : emif_io96b_hps_emif_io96b_hps_420_dyxenzq_emif_0_lpddr4_emif_io96b_cal_232_s5h5wki_cmp
		use entity emif_io96b_cal_232.emif_io96b_hps_emif_io96b_hps_420_dyxenzq_emif_0_lpddr4_emif_io96b_cal_232_s5h5wki;
begin

	num_calbus_periphs_check : if NUM_CALBUS_PERIPHS /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	num_calbus_plls_check : if NUM_CALBUS_PLLS /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	port_s_axil_mode_check : if PORT_S_AXIL_MODE /= "HARD_PATH" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	debug_tools_en_check : if DEBUG_TOOLS_EN /= false generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	port_m_axil_enable_check : if PORT_M_AXIL_ENABLE /= false generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	cal_0 : component emif_io96b_hps_emif_io96b_hps_420_dyxenzq_emif_0_lpddr4_emif_io96b_cal_232_s5h5wki_cmp
		generic map (
			NUM_CALBUS_PERIPHS => 1,
			NUM_CALBUS_PLLS    => 0,
			PORT_S_AXIL_MODE   => "HARD_PATH",
			DEBUG_TOOLS_EN     => false,
			PORT_M_AXIL_ENABLE => false
		)
		port map (
			periph_calbus_0             => periph_calbus_0,             --       calbus_periph_0.calbus
			periph_calbus_readdata_0    => periph_calbus_readdata_0,    --                      .calbus_readdata
			periph_calbus_param_table_0 => periph_calbus_param_table_0, --                      .calbus_param_table
			periph_calbus_1             => periph_calbus_1,             --       calbus_periph_1.calbus
			periph_calbus_readdata_1    => periph_calbus_readdata_1,    --                      .calbus_readdata
			periph_calbus_param_table_1 => periph_calbus_param_table_1, --                      .calbus_param_table
			pll_calbus_0                => pll_calbus_0,                --          calbus_pll_0.calbus
			pll_calbus_readdata_0       => pll_calbus_readdata_0,       --                      .calbus_readdata
			pll_calbus_1                => pll_calbus_1,                --          calbus_pll_1.calbus
			pll_calbus_readdata_1       => pll_calbus_readdata_1,       --                      .calbus_readdata
			pll_calbus_2                => pll_calbus_2,                --          calbus_pll_2.calbus
			pll_calbus_readdata_2       => pll_calbus_readdata_2,       --                      .calbus_readdata
			s0_axi4lite_clk             => s0_axi4lite_clk,             --       s0_axi4lite_clk.clk
			s0_axi4lite_rst_n           => s0_axi4lite_rst_n,           --     s0_axi4lite_rst_n.reset_n
			s0_axi4lite_awaddr          => s0_axi4lite_awaddr,          --           s0_axi4lite.awaddr
			s0_axi4lite_awvalid         => s0_axi4lite_awvalid,         --                      .awvalid
			s0_axi4lite_awready         => s0_axi4lite_awready,         --                      .awready
			s0_axi4lite_araddr          => s0_axi4lite_araddr,          --                      .araddr
			s0_axi4lite_arvalid         => s0_axi4lite_arvalid,         --                      .arvalid
			s0_axi4lite_arready         => s0_axi4lite_arready,         --                      .arready
			s0_axi4lite_wdata           => s0_axi4lite_wdata,           --                      .wdata
			s0_axi4lite_wvalid          => s0_axi4lite_wvalid,          --                      .wvalid
			s0_axi4lite_wready          => s0_axi4lite_wready,          --                      .wready
			s0_axi4lite_rresp           => s0_axi4lite_rresp,           --                      .rresp
			s0_axi4lite_rdata           => s0_axi4lite_rdata,           --                      .rdata
			s0_axi4lite_rvalid          => s0_axi4lite_rvalid,          --                      .rvalid
			s0_axi4lite_rready          => s0_axi4lite_rready,          --                      .rready
			s0_axi4lite_bresp           => s0_axi4lite_bresp,           --                      .bresp
			s0_axi4lite_bvalid          => s0_axi4lite_bvalid,          --                      .bvalid
			s0_axi4lite_bready          => s0_axi4lite_bready,          --                      .bready
			s0_axi4lite_awprot          => s0_axi4lite_awprot,          --                      .awprot
			s0_axi4lite_arprot          => s0_axi4lite_arprot,          --                      .arprot
			s0_axi4lite_wstrb           => s0_axi4lite_wstrb,           --                      .wstrb
			m0_axi4lite_awaddr          => m0_axi4lite_awaddr,          --           m0_axi4lite.awaddr
			m0_axi4lite_awvalid         => m0_axi4lite_awvalid,         --                      .awvalid
			m0_axi4lite_awready         => m0_axi4lite_awready,         --                      .awready
			m0_axi4lite_araddr          => m0_axi4lite_araddr,          --                      .araddr
			m0_axi4lite_arvalid         => m0_axi4lite_arvalid,         --                      .arvalid
			m0_axi4lite_arready         => m0_axi4lite_arready,         --                      .arready
			m0_axi4lite_wdata           => m0_axi4lite_wdata,           --                      .wdata
			m0_axi4lite_wvalid          => m0_axi4lite_wvalid,          --                      .wvalid
			m0_axi4lite_wready          => m0_axi4lite_wready,          --                      .wready
			m0_axi4lite_rresp           => m0_axi4lite_rresp,           --                      .rresp
			m0_axi4lite_rdata           => m0_axi4lite_rdata,           --                      .rdata
			m0_axi4lite_rvalid          => m0_axi4lite_rvalid,          --                      .rvalid
			m0_axi4lite_rready          => m0_axi4lite_rready,          --                      .rready
			m0_axi4lite_bresp           => m0_axi4lite_bresp,           --                      .bresp
			m0_axi4lite_bvalid          => m0_axi4lite_bvalid,          --                      .bvalid
			m0_axi4lite_bready          => m0_axi4lite_bready,          --                      .bready
			m0_axi4lite_awprot          => m0_axi4lite_awprot,          --                      .awprot
			m0_axi4lite_arprot          => m0_axi4lite_arprot,          --                      .arprot
			m0_axi4lite_wstrb           => m0_axi4lite_wstrb,           --                      .wstrb
			s0_noc_axi4lite_clk         => s0_noc_axi4lite_clk,         --   s0_noc_axi4lite_clk.clk
			s0_noc_axi4lite_rst_n       => s0_noc_axi4lite_rst_n,       -- s0_noc_axi4lite_rst_n.reset_n
			s0_noc_axi4lite_awaddr      => s0_noc_axi4lite_awaddr,      --       s0_noc_axi4lite.awaddr
			s0_noc_axi4lite_awvalid     => s0_noc_axi4lite_awvalid,     --                      .awvalid
			s0_noc_axi4lite_awready     => s0_noc_axi4lite_awready,     --                      .awready
			s0_noc_axi4lite_araddr      => s0_noc_axi4lite_araddr,      --                      .araddr
			s0_noc_axi4lite_arvalid     => s0_noc_axi4lite_arvalid,     --                      .arvalid
			s0_noc_axi4lite_arready     => s0_noc_axi4lite_arready,     --                      .arready
			s0_noc_axi4lite_wdata       => s0_noc_axi4lite_wdata,       --                      .wdata
			s0_noc_axi4lite_wvalid      => s0_noc_axi4lite_wvalid,      --                      .wvalid
			s0_noc_axi4lite_wready      => s0_noc_axi4lite_wready,      --                      .wready
			s0_noc_axi4lite_rresp       => s0_noc_axi4lite_rresp,       --                      .rresp
			s0_noc_axi4lite_rdata       => s0_noc_axi4lite_rdata,       --                      .rdata
			s0_noc_axi4lite_rvalid      => s0_noc_axi4lite_rvalid,      --                      .rvalid
			s0_noc_axi4lite_rready      => s0_noc_axi4lite_rready,      --                      .rready
			s0_noc_axi4lite_bresp       => s0_noc_axi4lite_bresp,       --                      .bresp
			s0_noc_axi4lite_bvalid      => s0_noc_axi4lite_bvalid,      --                      .bvalid
			s0_noc_axi4lite_bready      => s0_noc_axi4lite_bready,      --                      .bready
			s0_noc_axi4lite_awprot      => s0_noc_axi4lite_awprot,      --                      .awprot
			s0_noc_axi4lite_arprot      => s0_noc_axi4lite_arprot,      --                      .arprot
			s0_noc_axi4lite_wstrb       => s0_noc_axi4lite_wstrb,       --                      .wstrb
			tniul_rst_n                 => tniul_rst_n,                 --   s0_tniulite_reset_n.reset_n
			ls_to_cal                   => ls_to_cal,                   --                    ls.ls_to_cal
			ls_from_cal                 => ls_from_cal,                 --                      .ls_from_cal
			fbr_c2f_rst_n               => fbr_c2f_rst_n                --                      .fbr_c2f_rst_n
		);

end architecture rtl; -- of emif_io96b_hps_emif_io96b_hps_420_dyxenzq_emif_0_lpddr4_emif_io96b_lpddr4_emif_io96b_cal_420_65qugki
